### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Invalid Version: 10

### ISSUE THREAD

**Issue by MBurchard** [nklayman/vue-cli-plugin-electron-builder#1038]
**Describe the bug**
I know I'm a bit hasty, but I just started a new project with Vue 3 and the Electron builder.

That worked.

Then I updated several libs.

- @typescript-eslint/eslint-plugin: 2.34.0 > 4.1.0
- @typescript-eslint/parser: 2.34.0 > 4.1.0
- electron: 9.3.0 > 10.1.1
- eslint: 6.8.0 > 7.8.1
- sass-loader: 8.0.2 > 10.0.2
- typescript: 3.9.7 > 4.0.2

The application still builds but also shows a Warning:

```
yarn run v1.22.4
$ vue-cli-service electron:serve
 INFO  Starting development server...
10% building 2/2 modules 0 active(node:3260) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: 10
    at new SemVer (D:\Martin\Entwicklung\2020\electron-test\node_modules\vue-cli-plugin-electron-builder\node_modules\semver\classes\semver.js:41:13)
    at compare (D:\Martin\Entwicklung\2020\electron-test\node_modules\vue-cli-plugin-electron-builder\node_modules\semver\functions\compare.js:3:3)
    at Object.gte (D:\Martin\Entwicklung\2020\electron-test\node_modules\vue-cli-plugin-electron-builder\node_modules\semver\functions\gte.js:2:30)
    at chainWebpack (D:\Martin\Entwicklung\2020\electron-test\node_modules\vue-cli-plugin-electron-builder\lib\webpackConfig.js:50:16)
    at D:\Martin\Entwicklung\2020\electron-test\node_modules\vue-cli-plugin-electron-builder\index.js:51:5
    at D:\Martin\Entwicklung\2020\electron-test\node_modules\@vue\cli-service\lib\Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (D:\Martin\Entwicklung\2020\electron-test\node_modules\@vue\cli-service\lib\Service.js:236:26)
    at Service.resolveWebpackConfig (D:\Martin\Entwicklung\2020\electron-test\node_modules\@vue\cli-service\lib\Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (D:\Martin\Entwicklung\2020\electron-test\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
    at serve (D:\Martin\Entwicklung\2020\electron-test\node_modules\@vue\cli-service\lib\commands\serve.js:75:31)
    at Service.run (D:\Martin\Entwicklung\2020\electron-test\node_modules\@vue\cli-service\lib\Service.js:230:12)
    at D:\Martin\Entwicklung\2020\electron-test\node_modules\vue-cli-plugin-electron-builder\index.js:283:40
    at Service.run (D:\Martin\Entwicklung\2020\electron-test\node_modules\@vue\cli-service\lib\Service.js:230:12)
    at Object.<anonymous> (D:\Martin\Entwicklung\2020\electron-test\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
(node:3260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promis
e rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
98% after emitting CopyPlugin
```

It would be great if this warning from the electron builder plugin could be fixed.

**To Reproduce**

1. vue create electron-test  
  Vue CLI v4.5.6  
  ? Please pick a preset: Manually select features  
  ? Check the features needed for your project: Choose Vue version, Babel, TS, CSS Pre-processors, Linter  
  ? Choose a version of Vue.js that you want to start the project with 3.x (Preview)  
  ? Use class-style component syntax? Yes  
  ? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes  
  ? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with node-sass)  
  ? Pick a linter / formatter config: Standard  
  ? Pick additional lint features: Lint on save  
  ? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files  
  ? Save this as a preset for future projects? No  
2. vue add electron-builder  
  ? Choose Electron Version ^9.0.0
3. manually update libs  
  λ yarn outdated
  yarn outdated v1.22.4
  info Color legend :
   "red"    : Major Update backward-incompatible updates
   "yellow" : Minor Update backward-compatible features
   "green"  : Patch Update backward-compatible bug fixes
  Package                          Current Wanted Latest Package Type    URL
  @typescript-eslint/eslint-plugin 2.34.0  2.34.0 4.1.0  devDependencies https://github.com/typescript-eslint/typescript-eslint#readme  
  @typescript-eslint/parser        2.34.0  2.34.0 4.1.0  devDependencies https://github.com/typescript-eslint/typescript-eslint#readme  
  electron                         9.3.0   9.3.0  10.1.1 devDependencies https://github.com/electron/electron#readme  
  eslint                           6.8.0   6.8.0  7.8.1  devDependencies https://eslint.org  
  sass-loader                      8.0.2   8.0.2  10.0.2 devDependencies https://github.com/webpack-contrib/sass-loader  
  typescript                       3.9.7   3.9.7  4.0.2  devDependencies https://www.typescriptlang.org/  

**Expected behavior**
Should build without warning...

**Screenshots**

**Environment (please complete the following information):**
 - terminal output from running `vue info`:
```
λ vue info                                                    
                                                              
Environment Info:                                             
                                                              
  System:                                                     
    OS: Windows 10 10.0.19041                                 
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz     
  Binaries:                                                   
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE          
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD             
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD             
  Browsers:                                                   
    Chrome: Not Found                                         
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.51)    
  npmPackages:                                                
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0             
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2           
    @vue/babel-plugin-jsx:  1.0.0-rc.2                        
    @vue/babel-plugin-transform-vue-jsx:  1.1.2               
    @vue/babel-preset-app:  4.5.6                             
    @vue/babel-preset-jsx:  1.1.2                             
    @vue/babel-sugar-functional-vue:  1.1.2                   
    @vue/babel-sugar-inject-h:  1.1.2                         
    @vue/babel-sugar-v-model:  1.1.2                          
    @vue/babel-sugar-v-on:  1.1.2                             
    @vue/cli-overlay:  4.5.6                                  
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.6                    
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.6                   
    @vue/cli-plugin-router:  4.5.6                            
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.6               
    @vue/cli-plugin-vuex:  4.5.6                              
    @vue/cli-service: ~4.5.0 => 4.5.6                         
    @vue/cli-shared-utils:  4.5.6                             
    @vue/compiler-core:  3.0.0-rc.10                          
    @vue/compiler-dom:  3.0.0-rc.10                           
    @vue/compiler-sfc: ^3.0.0-0 => 3.0.0-rc.10                
    @vue/compiler-ssr:  3.0.0-rc.10                           
    @vue/component-compiler-utils:  3.2.0                     
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2              
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0            
    @vue/preload-webpack-plugin:  1.1.2                       
    @vue/reactivity:  3.0.0-rc.10                             
    @vue/runtime-core:  3.0.0-rc.10                           
    @vue/runtime-dom:  3.0.0-rc.10                            
    @vue/shared:  3.0.0-rc.10                                 
    @vue/web-component-wrapper:  1.2.0                        
    eslint-plugin-vue: ^7.0.0-0 => 7.0.0-beta.3               
    typescript: ^4 => 4.0.2                                   
    vue: ^3.0.0-0 => 3.0.0-rc.10                              
    vue-class-component: ^8.0.0-0 => 8.0.0-alpha.6            
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4
    vue-eslint-parser:  7.1.0                                 
    vue-hot-reload-api:  2.3.4                                
    vue-loader:  15.9.3 (16.0.0-beta.7)                       
    vue-style-loader:  4.1.2                                  
    vue-template-es2015-compiler:  1.9.1                      
  npmGlobalPackages:                                          
    @vue/cli: Not Found                                       
```

**Comment by nklayman** [comment]
I followed the steps you mentioned and did not get any error. Can you please create a repo that demonstrates the error or upload the `yarn.lock` file?

**Comment by MBurchard** [comment]
Although the problem is still present in the older project despite of updating all dependencies, I could not reproduce the problem when creating a new project.

**Comment by nklayman** [comment]
Dependencies of dependencies may not be upgraded with `yarn upgrade`. Try deleting your `yarn.lock` and `node_modules`, then reinstalling deps in the old project.
