### ISSUE TITLE
Error logs are not output correctly

### ISSUE THREAD

**Issue by nkprince007** [nklayman/vue-cli-plugin-electron-builder#105]
The logs from build errors / warnings in the main process are logged as an array.

```
Bundling main process:

[ './node_modules/node-gyp-build/index.js 13:9-32\nCritical dependency: the request of a dependency is an expression\n    at CommonJsRequireContextDependency.getWarnings (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)\n    at Compilation.reportDependencyErrorsAndWarnings (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:1327:24)\n    at Compilation.finish (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:1138:9)\n    at hooks.make.callAsync.err (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compiler.js:539:17)\n    at _err0 (eval at create (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)\n    at _addModuleChain (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:1066:12)\n    at processModuleDependencies.err (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:982:9)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n @ ./node_modules/bufferutil/index.js\n @ ./node_modules/ws/lib/buffer-util.js\n @ ./node_modules/ws/lib/receiver.js\n @ ./node_modules/ws/index.js\n @ ./src/main/websocket.ts\n @ ./src/main/index.ts\n @ multi ./src/main/index.ts',
  './node_modules/node-gyp-build/index.js 20:15-54\nCritical dependency: the request of a dependency is an expression\n    at CommonJsRequireContextDependency.getWarnings (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)\n    at Compilation.reportDependencyErrorsAndWarnings (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:1327:24)\n    at Compilation.finish (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:1138:9)\n    at hooks.make.callAsync.err (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compiler.js:539:17)\n    at _err0 (eval at create (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)\n    at _addModuleChain (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:1066:12)\n    at processModuleDependencies.err (/Users/nkprince007/Developer/src/gitlab.viperdev.io/pandas/electron/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:982:9)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n @ ./node_modules/bufferutil/index.js\n @ ./node_modules/ws/lib/buffer-util.js\n @ ./node_modules/ws/lib/receiver.js\n @ ./node_modules/ws/index.js\n @ ./src/main/websocket.ts\n @ ./src/main/index.ts\n @ multi ./src/main/index.ts' ]
```

It would rather make it reasonable to print them directly using `Array.join` as a string.

**Comment by nklayman** [comment]
I was thinking I could use the same logging method as [`@vue/cli-service`](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/formatStats.js). How does that sound? I'm pretty busy right now so I won't be able to implement it just yet.
