### ISSUE TITLE
Error: Cannot find module '@vue/cli-shared-utils'

### ISSUE THREAD

**Issue by NoahCardoza** [nklayman/vue-cli-plugin-electron-builder#1056]
**Describe the bug**
Error: Cannot find module '@vue/cli-shared-utils'

```
 ERROR  Error: Cannot find module '@vue/cli-shared-utils'
Require stack:
- /Users/vulcan/projects/warmer/node_modules/vue-cli-plugin-electron-builder/generator/index.js
- /Users/vulcan/.nvm/versions/node/v12.18.4/lib/node_modules/@vue/cli/node_modules/@vue/cli-shared-utils/lib/module.js
- /Users/vulcan/.nvm/versions/node/v12.18.4/lib/node_modules/@vue/cli/node_modules/@vue/cli-shared-utils/index.js
- /Users/vulcan/.nvm/versions/node/v12.18.4/lib/node_modules/@vue/cli/bin/vue.js
Error: Cannot find module '@vue/cli-shared-utils'
Require stack:
- /Users/vulcan/projects/warmer/node_modules/vue-cli-plugin-electron-builder/generator/index.js
- /Users/vulcan/.nvm/versions/node/v12.18.4/lib/node_modules/@vue/cli/node_modules/@vue/cli-shared-utils/lib/module.js
- /Users/vulcan/.nvm/versions/node/v12.18.4/lib/node_modules/@vue/cli/node_modules/@vue/cli-shared-utils/index.js
- /Users/vulcan/.nvm/versions/node/v12.18.4/lib/node_modules/@vue/cli/bin/vue.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/vulcan/projects/warmer/node_modules/vue-cli-plugin-electron-builder/generator/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
```

**To Reproduce**
`vue add electron-builder`

**Expected behavior**
No errors and project configured correctly.

**Screenshots**
N/A

**Environment (please complete the following information):**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: Not Found
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Not Found
    Firefox: 80.0
    Safari: 13.1.2
  npmPackages:
    babel-helper-vue-jsx-merge-props: ^2.0.3 => 2.0.3
    babel-plugin-jsx-vue-functional:  2.1.0
    babel-plugin-transform-vue-jsx: ^3.5.0 => 3.7.0
    babel-preset-vue:  1.2.1
    babel-preset-vue-app:  1.3.2
    eslint-plugin-vue: ^4.0.0 => 4.7.1
    jest-serializer-vue: ^0.3.0 => 0.3.0
    vue: ^2.5.2 => 2.6.12
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.4
    vue-jest: ^1.0.2 => 1.4.0
    vue-loader: ^13.3.0 => 13.7.3
    vue-style-loader: ^3.0.1 => 3.1.2
    vue-template-compiler: ^2.5.2 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 4.5.6
```

**Additional context**
This is a completely fresh project crated with `vue init webpack <project-name>`

The error stack seems like it's coming from the `vue-cli` package but I figured it might be worth asking here. It's been a while since I've used Vue.js.

**Comment by NoahCardoza** [comment]
Ok, think I fixed it by using `vue create <project-name>` and then `vue add electron-builder`!
