### ISSUE TITLE
Does this plugin work properly for you?

### ISSUE THREAD

**Issue by snapxtp** [nklayman/vue-cli-plugin-electron-builder#1067]
What happened to this beautiful plugin that I have used a few times without problems before?

It gave the following errors in my own project. I thought it was originated from me and created a blank and new test project. It only has vue-cli and electron in it. When I try to get a compilation for production, I get this error.

Anyone have a solution?
Thank you so much

at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
From previous event:
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at MacPackager.signApp (/Users/xxd/Desktop/works/shit/node_modules/app-builder-lib/src/macPackager.ts:330:27)
    at MacPackager.doPack (/Users/xxd/Desktop/works/shit/node_modules/app-builder-lib/src/platformPackager.ts:244:16)
    at MacPackager.pack (/Users/xxd/Desktop/works/shit/node_modules/app-builder-lib/src/macPackager.ts:130:7)
    at Packager.doBuild (/Users/xxd/Desktop/works/shit/node_modules/app-builder-lib/src/packager.ts:444:9)
    at executeFinally (/Users/xxd/Desktop/works/shit/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/xxd/Desktop/works/shit/node_modules/app-builder-lib/src/packager.ts:373:31)
    at Packager.build (/Users/xxd/Desktop/works/shit/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/xxd/Desktop/works/shit/node_modules/builder-util/src/promise.ts:12:14)
(node:15615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nklayman** [comment]
Just tried it myself and it works fine. Maybe try deleting `node_modules` and reinstalling deps. Also, it looks like the error you posted is missing some stuff at the beginning, can you post the full error you get?

**Comment by snapxtp** [comment]
I deleted the node_modules folder and updated the nodejs and npm. I tried again. electron: serve is working fine. I kept getting the following errors when I tried to build as an .app.

Note: I don't use Promise anywhere in my code.

node versiyon : v12.18.4
npm : 6.14.6 


"dependencies": {
    "core-js": "^3.6.5",
    "firebase": "^7.21.0",
    "lodash": "^4.17.20",
    "mobx": "^5.15.7",
    "mobx-vue": "^2.0.10",
    "moment": "^2.29.0",
    "v-offline": "^1.3.0",
    "vue": "^2.6.11",
    "vue-custom-scrollbar": "^1.3.0",
    "vue-router": "^3.2.0",
    "vue-uuid": "^2.0.2",
    "vuetify": "^2.2.11",
    "vuetify-toast-snackbar": "^0.6.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "electron": "^9.0.0",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.0",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.4",
    "vue-cli-plugin-vuetify": "~2.0.7",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.3.0"
  }
}

Building app with electron-builder:
  • electron-builder  version=22.8.1 os=19.6.0
  • description is missed in the package.json  appPackageFile=/Users/xxd/Desktop/works/test/dist_electron/bundled/package.json
  • author is missed in the package.json  appPackageFile=/Users/xxd/Desktop/works/test/dist_electron/bundled/package.json
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=9.3.2 appOutDir=dist_electron/mac
  • default Electron icon is used  reason=application icon is not set
  • signing         file=dist_electron/mac/test.app identityName=Apple Development: xxd (34...SS..AA) identityHash=8265BBC6A64E01ECA15E665488521444C613012 provisioningProfile=none
(node:21225) UnhandledPromiseRejectionWarning: Error: Command failed: codesign --verify --deep --strict --verbose=2 /Users/xxd/Desktop/works/test/dist_electron/mac/test.app
/Users/xxd/Desktop/works/test/dist_electron/mac/test.app: CSSMERR_TP_CERT_REVOKED
In architecture: x86_64

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
From previous event:
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at MacPackager.signApp (/Users/xxd/Desktop/works/test/node_modules/app-builder-lib/src/macPackager.ts:330:27)
    at MacPackager.doPack (/Users/xxd/Desktop/works/test/node_modules/app-builder-lib/src/platformPackager.ts:244:16)
    at MacPackager.pack (/Users/xxd/Desktop/works/test/node_modules/app-builder-lib/src/macPackager.ts:130:7)
    at Packager.doBuild (/Users/xxd/Desktop/works/test/node_modules/app-builder-lib/src/packager.ts:444:9)
    at executeFinally (/Users/xxd/Desktop/works/test/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/xxd/Desktop/works/test/node_modules/app-builder-lib/src/packager.ts:373:31)
    at Packager.build (/Users/xxd/Desktop/works/test/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/xxd/Desktop/works/test/node_modules/builder-util/src/promise.ts:12:14)
(node:21225) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21225) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by snapxtp** [comment]
I made an empty project where I just added electron-builder with vue-cli for testing.
I tried it on a different computer.

I have created an .app, but when I try to run it it doesn't open and asks if you want to delete it.

macOS Catalina 10.15.7
node:v10.19.0
npm:6.13.4

{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.0",
    "@vue/cli-plugin-router": "^4.5.0",
    "@vue/cli-service": "^4.5.0",
    "electron": "^8.0.0",
    "electron-devtools-installer": "^3.1.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-electron-builder": "^2.0.0-rc.4",
    "vue-template-compiler": "^2.6.11"
  }
}


Compiled successfully in 3701ms                                                                                                                                                           11:34:27 AM

  File                                   Size                                                                            Gzipped

  dist_electron/bundled/background.js    190.80 KiB                                                                      59.04 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=22.8.1 os=19.6.0
  • description is missed in the package.json  appPackageFile=/Users/xxd/Desktop/work/test/dist_electron/bundled/package.json
  • author is missed in the package.json  appPackageFile=/Users/xxd/Desktop/work/test/dist_electron/bundled/package.json
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.5.2 appOutDir=dist_electron/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v8.5.2/electron-v8.5.2-darwin-x64.zip size=66 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.5.2/electron-v8.5.2-darwin-x64.zip duration=13.375s
  • default Electron icon is used  reason=application icon is not set
  • signing         file=dist_electron/mac/test.app identityName=Apple Development: XXD (34VBV322sdfQ) identityHash=30C00208ECF22BC95CBB8B92327E18 provisioningProfile=none
(node:4379) UnhandledPromiseRejectionWarning: Error: Command failed: codesign --verify --deep --strict --verbose=2 /Users/xxd/Desktop/work/test/dist_electron/mac/test.app
/Users/xxd/Desktop/work/test/dist_electron/mac/test.app: CSSMERR_TP_CERT_REVOKED
In architecture: x86_64

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at MacPackager.signApp (/Users/xxd/Desktop/work/test/node_modules/app-builder-lib/src/macPackager.ts:330:27)
    at MacPackager.doPack (/Users/xxd/Desktop/work/test/node_modules/app-builder-lib/src/platformPackager.ts:244:16)
(node:4379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4379) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nklayman** [comment]
It looks like the error is being thrown by electron-builder while trying to sign your app. See the [Electron Builder signing](https://www.electron.build/code-signing) guide, something there may help you. If you still can't get it to work, you should open an issue on the [electron builder repo](https://github.com/electron-userland/electron-builder), as that is the tool that is throwing the error. This plugin just uses that tool, and likely isn't the cause of the issue.
