### ISSUE TITLE
TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by andywampir** [nklayman/vue-cli-plugin-electron-builder#1149]
**Describe the bug**
`electron:serve` throws error `TypeError: Cannot read property 'getPath' of undefined`

Terminal output:
```
webpack:///C:/Users/wampir/projects/test/node_modules/.pnpm/vue-cli-plugin-electron-builder@2.0.0-rc.5/node_modules/vue-cli-plugin-e
lectron-builder/lib/installVueDevtools/utils.js?:19
  const savePath = (electron__WEBPACK_IMPORTED_MODULE_0__["remote"] || electron__WEBPACK_IMPORTED_MODULE_0___default.a).app.getPath(
'userData')
                                                                                                                            ^
TypeError: Cannot read property 'getPath' of undefined
    at getPath (webpack:///C:/Users/wampir/projects/test/node_modules/.pnpm/vue-cli-plugin-electron-builder@2.0.0-rc.5/node_modules/
vue-cli-plugin-electron-builder/lib/installVueDevtools/utils.js?:19:125)
    at getIDMapPath (webpack:///C:/Users/wampir/projects/test/node_modules/.pnpm/vue-cli-plugin-electron-builder@2.0.0-rc.5/node_mod
ules/vue-cli-plugin-electron-builder/lib/installVueDevtools/index.js?:20:134)
    at eval (webpack:///C:/Users/wampir/projects/test/node_modules/.pnpm/vue-cli-plugin-electron-builder@2.0.0-rc.5/node_modules/vue
-cli-plugin-electron-builder/lib/installVueDevtools/index.js?:21:58)
    at Module../node_modules/.pnpm/vue-cli-plugin-electron-builder@2.0.0-rc.5/node_modules/vue-cli-plugin-electron-builder/lib/insta
llVueDevtools/index.js (c:\Users\wampir\projects\test\dist_electron\index.js:1654:1)
    at __webpack_require__ (c:\Users\wampir\projects\test\dist_electron\index.js:20:30)
    at eval (webpack:///C:/Users/wampir/projects/test/node_modules/.pnpm/vue-cli-plugin-electron-builder@2.0.0-rc.5/node_modules/vue
-cli-plugin-electron-builder/lib/index.js?:2:77)
    at Module../node_modules/.pnpm/vue-cli-plugin-electron-builder@2.0.0-rc.5/node_modules/vue-cli-plugin-electron-builder/lib/index
.js (c:\Users\wampir\projects\test\dist_electron\index.js:1630:1)
    at __webpack_require__ (c:\Users\wampir\projects\test\dist_electron\index.js:20:30)
    at eval (webpack:///./src/background.ts?:4:93)
    at Module../src/background.ts (c:\Users\wampir\projects\test\dist_electron\index.js:1722:1)
```

**To Reproduce**

1. `vue create`
2. `vue add electron-builder`
3. `yarn electron:serve`

**Expected behavior**
Launching Electron instance without any errors

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: -
 - (if possible) link to your repo: -
 - terminal output from running `vue info`:
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.41)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.9
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.9
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.9
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.9
    @vue/cli-plugin-router: ~4.5.0 => 4.5.9
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.9
    @vue/cli-plugin-vuex:  4.5.9
    @vue/cli-service: ~4.5.0 => 4.5.9
    @vue/cli-shared-utils:  4.5.9
    @vue/compiler-core:  3.0.2
    @vue/compiler-dom:  3.0.2
    @vue/compiler-sfc: ^3.0.0 => 3.0.2
    @vue/compiler-ssr:  3.0.2
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.0.2
    @vue/runtime-core:  3.0.2
    @vue/runtime-dom:  3.0.2
    @vue/shared:  3.0.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.0.0-0 => 7.1.0
    typescript: ~3.9.3 => 3.9.7
    vue: ^3.0.0 => 3.0.2
    vue-cli-plugin-electron-builder: ~2.0.0-rc.5 => 2.0.0-rc.5
    vue-eslint-parser:  7.1.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.5 (16.0.0-rc.2)
    vue-router: ^4.0.0-0 => 4.0.0-rc.5
    vue-style-loader:  4.1.2
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Additional context**
I've tried solution from [issue #46](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/46#issuecomment-413452005) but it's not work for me

**Comment by andywampir** [comment]
It's kind of Electron related issue, but no one solutions can help me, maybe here i'll found one that truly helps

**Comment by nklayman** [comment]
It works fine for me. Can you please upload the repo so that I can test it myself?

**Comment by andywampir** [comment]
I found one strange solution for me, if i run command `yarn electron:serve` as an administrator it's work perfectly.
I don't understand why `electron` needs administration privilege to work properly

**Comment by andywampir** [comment]
I'll close this issue and try ask in `electron` repo: why it's needs run as administrator.
