### ISSUE TITLE
Using bpmn-js pack failed

### ISSUE THREAD

**Issue by mazhewei** [nklayman/vue-cli-plugin-electron-builder#1187]
Hi. I'm try to create a bpmn modeler app with these deps:
```
"bpmn-js": "^8.0.0",
"webpack": "^4.0.0",
"electron": "^10.1.6",
"vue-cli-plugin-electron-builder": "^2.0.0-rc.4",
"vue": "^2.6.12",
```
when i import like this,
```
import BpmnViewer from 'bpmn-js';
```
i get this error in browser console:
```
D:\myprojectpath\node_modules\bpmn-js\index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export {
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:88:7)
    at createScript (vm.js:263:10)
    at Object.runInThisContext (vm.js:311:10)
    at wrapSafe (internal/modules/cjs/loader.js:1038:15)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
```

i search official forum, one similar problem is https://forum.bpmn.io/t/error-bundling-bpmn-js-unexpected-token-export/2536

Ans is: You must use a ES module aware bundler.

I'm sure project is use webpack4.

here is another similar problem https://github.com/SimulatedGREG/electron-vue/issues/915

i think that is because the dependency was not include by webpack, and i can not find builder options.

any suggests?

thanks!

**Comment by nklayman** [comment]
The issue is caused because this plugin incorrectly identifies bpmn-js as a native dep, and doesn't compile it with webpack. You have two options to fix this, both of which require you to update your `vue.config.js`:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      // Option 1: Manually declare bpmn-js as a non-external
      externals: ['!bpmn-js'],
      // Options 2: use the new native dep checker, which will correctly identify bpmn-js as a non-native dep
      experimentalNativeDepCheck: true
    }
  }
}
