### ISSUE TITLE
Cannot pass args to electron-builder due to yargs kebab-case mangling

### ISSUE THREAD

**Issue by pattrickrice** [nklayman/vue-cli-plugin-electron-builder#1191]
I'm looking to pass additional args to electron-builder, specifically --projectDir, I don't believe that's possible with the current configuration. What happens is that yargs parses projectDir, but also adds `project-dir`. Electron-Builder validates the args passed to it, so an error is thrown when the kebab case is passed.

```bash
➜  ~ vue create hello-world  


Vue CLI v4.4.5
┌─────────────────────────────────────────┐
│                                         │
│   New version available 4.4.5 → 4.5.9   │
│                                         │
└─────────────────────────────────────────┘

? Please pick a preset: default (babel, eslint)


Vue CLI v4.4.5
✨  Creating project in /home/price/hello-world.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

yarn install v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...

success Saved lockfile.
Done in 8.18s.
🚀  Invoking generators...
📦  Installing additional dependencies...

yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 3.12s.
⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project hello-world.
👉  Get started with the following commands:

 $ cd hello-world
 $ yarn serve

➜  ~ cd hello-world 
➜  hello-world git:(master) vue add electron-builder

📦  Installing vue-cli-plugin-electron-builder...

yarn add v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 79 new dependencies.
info Direct dependencies
└─ vue-cli-plugin-electron-builder@2.0.0-rc.5
info All dependencies
├─ @develar/schema-utils@2.6.5
├─ @npmcli/move-file@1.0.1
├─ @sindresorhus/is@0.14.0
├─ @szmarczak/http-timer@1.1.2
├─ @types/debug@4.1.5
├─ @types/yargs-parser@15.0.0
├─ @types/yargs@15.0.12
├─ ansi-align@3.0.0
├─ app-builder-bin@3.5.10
├─ at-least-node@1.0.0
├─ boxen@4.2.0
├─ cacheable-request@6.1.0
├─ chromium-pickle-js@0.2.0
├─ ci-info@2.0.0
├─ cli-boxes@2.2.1
├─ clone-response@1.0.2
├─ configstore@5.0.1
├─ crypto-random-string@2.0.0
├─ decompress-response@3.3.0
├─ deep-extend@0.6.0
├─ defer-to-connect@1.1.3
├─ dmg-builder@22.9.1
├─ duplexer3@0.1.4
├─ electron-builder@22.9.1
├─ electron-publish@22.9.1
├─ escape-goat@2.1.1
├─ filelist@1.0.1
├─ friendly-errors-webpack-plugin@1.7.0
├─ global-dirs@2.1.0
├─ got@9.6.0
├─ has-ansi@2.0.0
├─ has-yarn@2.1.0
├─ hosted-git-info@3.0.7
├─ http-cache-semantics@4.1.0
├─ immediate@3.0.6
├─ import-lazy@2.1.0
├─ ini@1.3.7
├─ is-installed-globally@0.3.2
├─ is-npm@4.0.0
├─ is-yarn-global@0.3.0
├─ isbinaryfile@4.0.6
├─ jake@10.8.2
├─ json-buffer@3.0.0
├─ jszip@3.5.0
├─ keyv@3.1.0
├─ latest-version@5.1.0
├─ lie@3.3.0
├─ lodash.merge@4.6.2
├─ lowercase-keys@1.0.1
├─ minizlib@2.1.2
├─ p-cancelable@1.1.0
├─ package-json@6.5.0
├─ pumpify@2.0.1
├─ pupa@2.1.1
├─ registry-auth-token@4.2.1
├─ registry-url@5.1.0
├─ responselike@1.0.2
├─ semver-diff@3.1.1
├─ set-immediate-shim@1.0.1
├─ shebang-loader@0.0.1
├─ split2@3.2.2
├─ stat-mode@1.0.0
├─ tar@6.0.5
├─ term-size@2.2.1
├─ through2-filter@3.0.0
├─ through2-map@3.0.0
├─ to-readable-stream@1.0.0
├─ truncate-utf8-bytes@1.0.2
├─ typedarray-to-buffer@3.1.5
├─ unique-string@2.0.0
├─ unzip-crx@0.2.0
├─ update-notifier@4.1.3
├─ url-parse-lax@3.0.0
├─ utf8-byte-length@1.0.4
├─ vue-cli-plugin-electron-builder@2.0.0-rc.5
├─ widest-line@3.1.0
├─ write-file-atomic@3.0.3
├─ yaku@0.16.7
└─ yocto-queue@0.1.0
Done in 3.77s.
✔  Successfully installed plugin: vue-cli-plugin-electron-builder

? Choose Electron Version ^9.0.0

🚀  Invoking generator for vue-cli-plugin-electron-builder...
📦  Installing additional dependencies...

yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder  version=22.9.1
Done in 5.12s.
⚓  Running completion hooks...

✔  Successfully invoked generator for plugin: vue-cli-plugin-electron-builder
➜  hello-world git:(master) ✗ yarn electron:build --projectDir=../     
yarn run v1.22.10
$ vue-cli-service electron:build --projectDir=../
 INFO  Bundling render process:

⠦  Building modern bundle for production...

 DONE  Compiled successfully in 3258ms                                   6:53:33 PM

  File                                       Size              Gzipped

  dist_electron/bundled/js/chunk-vendors.    74.81 KiB         26.82 KiB
  e50bb16d.js
  dist_electron/bundled/js/app.579f0ebb.j    4.55 KiB          1.62 KiB
  s
  dist_electron/bundled/css/app.fb0c6e1c.    0.33 KiB          0.23 KiB
  css

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron/bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
      
⠇  Bundling main process...

 DONE  Compiled successfully in 4776ms                                   6:53:38 PM

  File                                   Size                Gzipped

  dist_electron/bundled/background.js    199.47 KiB          61.69 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=22.9.1 os=4.4.0-148-generic

/home/price/hello-world/node_modules/app-builder-lib/src/index.ts:44
      throw new InvalidConfigurationError(`Unknown option "${optionName}"`)
            ^
Error: Unknown option "project-dir"
    at checkBuildRequestOptions (/home/price/hello-world/node_modules/app-builder-lib/src/index.ts:44:13)
    at build (/home/price/hello-world/node_modules/app-builder-lib/src/index.ts:50:3)
    at Object.build (/home/price/hello-world/node_modules/electron-builder/src/builder.ts:218:10)
    at buildApp (/home/price/hello-world/node_modules/vue-cli-plugin-electron-builder/index.js:242:12)
    at /home/price/hello-world/node_modules/vue-cli-plugin-electron-builder/index.js:223:15
    at finalCallback (/home/price/hello-world/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/price/hello-world/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/price/hello-world/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (/home/price/hello-world/node_modules/tapable/lib/Hook.js:154:20)
    at /home/price/hello-world/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/price/hello-world/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/price/hello-world/node_modules/webpack/lib/Compiler.js:298:10
    at /home/price/hello-world/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/price/hello-world/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/price/hello-world/node_modules/tapable/lib/Hook.js:154:20)
    at /home/price/hello-world/node_modules/webpack/lib/Compiler.js:482:27
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nklayman** [comment]
Changing the project dir will likely break the build process as this plugin relies on it being the root of the vue app. You can use `--project=../` instead of `--projectDir` and it should work fine then, as there are no capital letters.
