### ISSUE TITLE
Cannot find external module on Windows

### ISSUE THREAD

**Issue by claudia-romano** [nklayman/vue-cli-plugin-electron-builder#1197]
Hi, thanks for this great plugin!

I'm using knex.js and sqlite3 for my app database. they are both set as externals in the config file. 
```
module.exports = {
  // ...
  pluginOptions: {
    electronBuilder: {
      externals: ['knex','sqlite3'],
      nodeModulesPath: ['../../node_modules', './node_modules']
    }
  }
}
```
It is working fine on Mac, while I'm having issues on Windows 10 (production env). Here's the error message I get when trying to connect to the db:
```
Knex: run
$ npm install sqlite3 --save
Cannot find module 'C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\sqlite3\lib\binding\electron-v6.1-win32-ia32\node_sqlite3.node'
Require stack:
- C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\sqlite3\lib\sqlite3-binding.js
- C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js
- C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\knex\lib\dialects\sqlite3\index.js
- C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\knex\lib\knex.js
- C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\knex\lib\index.js
- C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\knex\knex.js
- C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\background.js
- 
    at Client_SQLite3.initializeDriver (C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\knex\lib\client.js:235:13)
    at Client_SQLite3.Client (C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\knex\lib\client.js:69:10)
    at new Client_SQLite3 (C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\knex\lib\dialects\sqlite3\index.js:17:10)
    at Knex (C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\node_modules\knex\lib\knex.js:53:28)
    at C:\Users\userName\AppData\Local\Programs\appName\resources\app.asar\background.js:308:123404
```
I've created the Windows app release on Mac using the `npm run electron:build -- --win --ia32` command.

Do you have any idea why this may be happening? Thank you.

**Comment by claudia-romano** [comment]
It turned out the problem is building the Windows release on a Mac. Using a Windows machine fixes it. Thanks!
