### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by Carolineliu** [nklayman/vue-cli-plugin-electron-builder#1223]
**Is your feature request related to a problem? Please describe.**

version:^2.0.0-rc.5
+ npm run build

> vue-web@0.1.0 build /var/jenkins_home/workspace/vue-web_dev
> vue-cli-service build

/var/jenkins_home/workspace/vue-web_dev/node_modules/vue-cli-plugin-electron-builder/node_modules/p-limit/index.js:29
		} catch {}
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/jenkins_home/workspace/vue-web_dev/node_modules/vue-cli-plugin-electron-builder/node_modules/terser-webpack-plugin/dist/index.js:26:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Carolineliu** [comment]
I found the problem
