### ISSUE TITLE
Can't build properly with a Prisma dependency

### ISSUE THREAD

**Issue by clementvp** [nklayman/vue-cli-plugin-electron-builder#1247]
**Describe the bug**

Can't Build the app with a [Prisma](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-node-postgres) Dependency. Prisma is an ORM with a Query Engine.

The command electron:serve works fine.

**To Reproduce**

Clone this [repo ](https://github.com/clementvp/vue-electron-prisma-test)  

Install dependencies with npm install.  It should migrate database and generate the prisma-client.

Launch a server with npm run electron:serve  (works fine)

Try to build with npm run electron:build (build is fine)

But when I try to launch the app, I've got:  

```
Uncaught Exception:
Error: Cannot find module '.prisma/client'
Require stack:
- /Users/clement/Desktop/vue-electron-prisma/dist_electron/mac/vue-electron-prisma.app/Contents/Resources/app.asar/node_modules/@prisma/client/index.js
- /Users/clement/Desktop/vue-electron-prisma/dist_electron/mac/vue-electron-prisma.app/Contents/Resources/app.asar/background.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/clement/Desktop/vue-electron-prisma/dist_electron/mac/vue-electron-prisma.app/Contents/Resources/app.asar/node_modules/@prisma/client/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
```

My vue.config.js looks like this:  

```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['@prisma/client'],
      extraResources: ['src/data.db'],
    },
  },
};
```

Note the externals and extraResources to be in accordance with the prisma use.

My vue info:  

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Not Found
    Firefox: 85.0.2
    Safari: 14.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.11 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.11 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.11 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.11 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.11 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.11 
    @vue/cli-service: ~4.5.0 => 4.5.11 
    @vue/cli-shared-utils:  4.5.11 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.12 
    vue-cli-plugin-electron-builder: ~2.0.0-rc.6 => 2.0.0-rc.6 
    vue-eslint-parser:  7.5.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.6 (16.1.2)
    vue-router: ^3.2.0 => 3.5.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.4.0 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.5.9
```
I use sqlite with Prisma (see ./prisma/schema.prisma), my db file is under src.

I tried to add `.prisma/client` to the externals, but I've got the same error.

**Expected behavior**

Build fine, without errors at launch.

Seems to be a prisma webpack issue, maybe :/
And i'm a noob with webpack.

I love so much VCP elctron builder. <3

**Comment by nklayman** [comment]
Seems like there is a weird issue with electron-builder failing to package prisma into the bundle properly. As a workaround, set your `vue.config.js` to:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['@prisma/client'],
      builderOptions: {
        extraResources: [
          'src/data.db',
          'node_modules/.prisma/**',
          'node_modules/@prisma/client/**',
        ],
      },
    },
  },
};
```

**Comment by clementvp** [comment]
Yes, I confirm, the workaround works with the extraResources under builderOptions. Thank you for your time.
