### ISSUE TITLE
Node Serialport doesn't work after building

### ISSUE THREAD

**Issue by reverse28** [nklayman/vue-cli-plugin-electron-builder#1295]
Hello. 
I'm having trouble getting Node Serialport to work after running **electron: build**.

Serial port works fine with **electron: serve** when added to vue-config
```
electronBuilder: {
             externals: ['serialport'],
             nodeModulesPath: ['../../node_modules', './node_modules']
}
```
and running **electron-rebuild -f -w serialport**

But as soon as I try to execute **electron: build** it stops working in the generated package and also throws an error the next time I run **electron: serve**.

> (node:51980) UnhandledPromiseRejectionWarning: TypeError: Third argument must be a function
>     at internal/util.js:297:30
>     at new Promise (<anonymous>)
>     at open (internal/util.js:296:12)
>     at WindowsBinding.open (******\node_modules\@serialport\bindings\lib\win32.js:56:22)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 
> (node:51980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

> (node:51980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> (node:51980) ExtensionLoadWarning: Warnings loading extension at 
> ****\extensions\nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

> (node:51980) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

 "serialport": "^9.0.7",
 "vue": "^2.6.11",
 "electron": "^11.0.0",
"node.js": v14.15.0

How can i solve this problem?

**Comment by reverse28** [comment]
i solved this problem by adding
```
 electronBuilder: {
			builderOptions: {
				  "npmRebuild": false
			}
                    }
```
in **vue-config file**
