### ISSUE TITLE
webpack can not work with binding

### ISSUE THREAD

**Issue by JsBlueCat** [nklayman/vue-cli-plugin-electron-builder#1321]
**Describe the bug**
```
 INFO  Launching Electron...
App threw an error during load
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at dirname (path.js:583:5)
    at Function.getRoot (webpack:///./node_modules/bindings/bindings.js?:146:13)
    at eval (webpack:///./src/background.js?:106:19)
    at Module../src/background.js (D:\stereoRectify\dist_electron\index.js:1802:1)
    at __webpack_require__ (D:\stereoRectify\dist_electron\index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (D:\stereoRectify\dist_electron\index.js:1813:1)
    at __webpack_require__ (D:\stereoRectify\dist_electron\index.js:20:30)
    at D:\stereoRectify\dist_electron\index.js:84:18
```
**To Reproduce**
```
var addon = require('bindings');
console.log(addon.getRoot())
```
add this line to background.js

**Expected behavior**

 the path is conflict with webpack

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:
window x64 

@jayvdb @lingo @Desuuuu

**Comment by JsBlueCat** [comment]
this is can be solved by use electron-rebuild.
the node-gyp depends on the node.dll in your system version. how ever the electron contains the other node version. 
the api in it is conflict. so we may need to rebuild it 
```
npm install -i electron-rebuild
./node_modules/bin/electron-rebuild.cmd
```
maybe this help
