### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by logue** [nklayman/vue-cli-plugin-electron-builder#1334]
**Describe the bug**
When I execute `vue add electron-builder` in comman line, the error `Can not create a string longer than 0x1fffffe8 characters` occurs.

**To Reproduce**
Occurs on Windows 10. 
Reproduced even if the directory is set to a higher level or hyphens are removed from the project folder name.

**Expected behavior**
Subsequent processing should be executed normally.

**Screenshots**

```
PS [Project Directory]> vue invoke electron-builder
 WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes
 ERROR  Error: Cannot create a string longer than 0x1fffffe8 characters
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at Object.readFileSync (node:fs:446:41)
    at readFiles (C:\Users\[user]\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\readFiles.js:21:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runGenerator (C:\Users\[user]\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:103:12)
    at async invoke (C:\Users\[user]\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)
```

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: No
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.77)
  npmPackages:
    @samhammer/vue-cli-plugin-stylelint: ~2.0.1 => 2.0.1
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.5
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.12
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.12
    @vue/cli-plugin-babel: ^4.5.12 => 4.5.12
    @vue/cli-plugin-eslint: ^4.5.12 => 4.5.12
    @vue/cli-plugin-router: ^4.5.12 => 4.5.12
    @vue/cli-plugin-typescript: ^4.5.12 => 4.5.12
    @vue/cli-plugin-vuex: ^4.5.12 => 4.5.12
    @vue/cli-service: ^4.5.12 => 4.5.12
    @vue/cli-shared-utils:  3.12.1 (4.5.12)
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^7.9.0 => 7.9.0
    typescript: ^4.2.4 => 4.2.4 (3.9.9)
    vue: ^2.6.12 => 2.6.12
    vue-axios: ^2.1.5 => 2.1.5
    vue-class-component: ^7.2.6 => 7.2.6
    vue-cli-plugin-electron-builder: * => 2.0.0-rc.6
    vue-cli-plugin-vuetify: ~2.3.1 => 2.3.1
    vue-electron: ^1.0.6 => 1.0.6
    vue-eslint-parser:  7.6.0 (7.1.1)
    vue-force-next-tick: ^1.1.0 => 1.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader: ^15.9.6 => 15.9.6 (16.2.0)
    vue-property-decorator: ^9.1.2 => 9.1.2
    vue-router: ^3.5.1 => 3.5.1
    vue-style-loader:  4.1.3
    vue-template-compiler: ^2.6.12 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuetify: ^2.4.11 => 2.4.11
    vuetify-loader: ^1.7.2 => 1.7.2
    vuex: ^3.6.2 => 3.6.2
    vuex-persistedstate: * => 4.0.0-beta.3
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by nklayman** [comment]
What happens if you try and add a different plugin? Seems like this is an issue with vue CLI or node, not this plugin specifically. If that works, can you share the repo you are trying to add this plugin to?

**Comment by logue** [comment]
The cause was that the version of Electron was 12 in the batch update. After all, I downgraded to 11 and dealt with it.

**Comment by nklayman** [comment]
Ok, glad you found a solution. Is it ok to close this now?
