### ISSUE TITLE
Minimal Spectron usage example

### ISSUE THREAD

**Issue by Djiit** [nklayman/vue-cli-plugin-electron-builder#136]
I'm reading the Testing and Debugging docs, but I can't make the snippet work with Spectron.

Is there any chance you could provide us a minimal example (in a separate repository maybe) ?

Thanks !

**Comment by nklayman** [comment]
Try this:
```javascript
const { testWithSpectron } = require('vue-cli-plugin-electron-builder')
jest.setTimeout(50000)

test('Window Loads Properly', async () => {
  // Wait for dev server to start
  const { app, stopServe } = await testWithSpectron()
  const win = app.browserWindow
  const client = app.client

  // Window was created
  expect(await client.getWindowCount()).toBe(1)
  // It is not minimized
  expect(await win.isMinimized()).toBe(false)
  // Window is visible
  expect(await win.isVisible()).toBe(true)
  // Size is correct
  const { width, height } = await win.getBounds()
  expect(width).toBeGreaterThan(0)
  expect(height).toBeGreaterThan(0)
  // App is loaded properly
  expect(
    /Welcome to Your Vue\.js (\+ TypeScript )?App/.test(
      await client.getHTML('#app')
    )
  ).toBe(true)

  await stopServe()
})
```

**Comment by Djiit** [comment]
Hi, here is the result :

```
➜  desktop-app git:(chore-e2e-test) ✗ yarn test:e2e
yarn run v1.12.3
$ vue-cli-service test:unit --testMatch=**/tests/e2e/**/*.spec.js
jest-haste-map: @providesModule naming collision:
  Duplicate module name: crtx
  Paths: /Users/jtanay/Projects/misc/desktop-app/package.json collides with /Users/jtanay/Projects/misc/desktop-app/dist_electron/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
 FAIL  tests/e2e/main.spec.js (52.499s)
  ✕ Window Loads Properly (50014ms)

  ● Window Loads Properly

    Timeout - Async callback was not invoked within the 50000ms timeout specified by jest.setTimeout.

      2 | jest.setTimeout(50000)
      3 |
    > 4 | test('Window Loads Properly', async () => {
        | ^
      5 |   // Wait for dev server to start
      6 |   const { app, stopServe } = await testWithSpectron()
      7 |   const win = app.browserWindow

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Object.test (tests/e2e/main.spec.js:4:1)

Snapshot Summary
 › 3 snapshot files obsolete from 3 test suites. To remove them all, re-run jest with `-u`.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   3 files obsolete, 0 total
Time:        53.085s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

I had to manually kill the process (Ctrl+C).

Any ideas ?

**Comment by nklayman** [comment]
Try replacing
```javascript
  if (isDevelopment) {
```
with
```javascript
  if (isDevelopment || process.env.IS_TEST) {
```

also try deleting the `dist_electron` folder before running the tests

**Comment by Djiit** [comment]
Same results here, but my app opened just after the timeout. The test had already failed.

**Comment by nklayman** [comment]
Try increasing the time out, or just running it again as it should be cached now.

**Comment by Djiit** [comment]
Right! It did the trick, but now your first test is failing because of getWindowsCount being `2`.

**Comment by nklayman** [comment]
I believe that is an issue with spectron. You can fix it with the following code:
```javascript
  setTimeout(async () => expect(await client.getWindowCount()).toBe(1), 5000)
```
I got this from https://github.com/electron/spectron/issues/60#issuecomment-328446679. You can open an additional issue in the Spectron repository as well.
