### ISSUE TITLE
`vue-cli-service electron:build --win `  Unsuccessful execution

### ISSUE THREAD

**Issue by zhump** [nklayman/vue-cli-plugin-electron-builder#142]
node:v8.13.0
electron:v3.0
```
INFO  Building app with electron-builder:
• electron-builder version=20.36.2
• description is missed in the package.json appPackageFile=/Users/aaaa/Documents/ttttt/aa/aa/dist_electron/bundled/package.json
• author is missed in the package.json appPackageFile=/Users/aaaa/Documents/ttttt/aa/aa/dist_electron/bundled/package.json
• writing effective config file=dist_electron/builder-effective-config.yaml
• no native production dependencies
• packaging       platform=win32 arch=x64 electron=3.0.10 appOutDir=dist_electron/win-unpacked
⨯ error: exit status 1
path: /Users/aaaa/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine
args: /Users/aaaa/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine /Users/aaaa/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.4.0/rcedit-ia32.exe /Users/aaaa/Documents/ttttt/aa/aa/dist_electron/win-unpacked/aa.exe --set-version-string FileDescription aa --set-version-string ProductName aa --set-version-string LegalCopyright Copyright © 2018 aa --set-file-version 0.1.0 --set-product-version 0.1.0.0 --set-version-string InternalName aa --set-version-string OriginalFilename 
output: 
error output:%!(EXTRA string=wine: failed to initialize: dlopen(/tmp/wine-stage/wine/usr/lib/wine/ntdll.dll.so, 258): image not found
)
github.com/develar/app-builder/pkg/util.Execute
/Users/develar/Documents/app-builder/pkg/util/util.go:73
github.com/develar/app-builder/pkg/wine.execWine
/Users/develar/Documents/app-builder/pkg/wine/wine.go:75
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
/Users/develar/Documents/app-builder/pkg/wine/wine.go:42
github.com/alecthomas/kingpin.(*actionMixin).applyActions
/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
/Users/develar/Documents/app-builder/main.go:73
runtime.main
/usr/local/Cellar/go/1.11.2/libexec/src/runtime/proc.go:201
runtime.goexit
/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:1333

ERROR  Error: /Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-bin/mac/app-builder exited with code 1
Error: /Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-bin/mac/app-builder exited with code 1
  at ChildProcess.childProcess.once.code (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/builder-util/src/util.ts:244:14)
  at Object.onceWrapper (events.js:273:13)
  at ChildProcess.emit (events.js:182:13)
  at ChildProcess.EventEmitter.emit (domain.js:442:20)
  at maybeClose (internal/child_process.js:962:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
  at runCallback (timers.js:705:18)
  at tryOnImmediate (timers.js:676:5)
  at processImmediate (timers.js:658:5)
  at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
  at WinPackager.signAndEditResources (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/winPackager.ts:251:158)
  at _bluebirdLst.default.map.file (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/winPackager.ts:354:21)
  at go$readdir$cb (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/graceful-fs/graceful-fs.js:162:14)
  at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/winPackager.ts:352:27
  at Generator.next (<anonymous>)
From previous event:
  at WinPackager.signApp (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/winPackager.ts:346:73)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/platformPackager.ts:250:16
  at Generator.next (<anonymous>)
  at runCallback (timers.js:705:18)
  at tryOnImmediate (timers.js:676:5)
  at processImmediate (timers.js:658:5)
  at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
  at WinPackager.doPack (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/platformPackager.ts:113:16
  at Generator.next (<anonymous>)
From previous event:
  at WinPackager.pack (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/packager.ts:406:24
  at Generator.next (<anonymous>)
  at xfs.stat (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/graceful-fs/polyfills.js:285:20
  at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
  at Packager.doBuild (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/packager.ts:372:24)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/packager.ts:342:57
  at Generator.next (<anonymous>)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/graceful-fs/graceful-fs.js:111:16
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/graceful-fs/graceful-fs.js:45:10
  at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
  at Packager._build (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/packager.ts:311:133)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/packager.ts:307:23
  at Generator.next (<anonymous>)
  at runCallback (timers.js:705:18)
  at tryOnImmediate (timers.js:676:5)
  at processImmediate (timers.js:658:5)
  at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
  at Packager.build (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/packager.ts:264:14)
  at build (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/app-builder-lib/src/index.ts:59:28)
  at Object.build (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/electron-builder/src/builder.ts:227:10)
  at buildApp (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/vue-cli-plugin-electron-builder/index.js:173:14)
  at bundle.run (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/vue-cli-plugin-electron-builder/index.js:155:15)
  at finalCallback (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/webpack/lib/Compiler.js:210:39)
  at hooks.done.callAsync.err (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/webpack/lib/Compiler.js:259:14)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
  at AsyncSeriesHook.lazyCompileHook (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/tapable/lib/Hook.js:154:20)
  at emitRecords.err (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/webpack/lib/Compiler.js:257:22)
  at Compiler.emitRecords (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/webpack/lib/Compiler.js:371:39)
  at emitAssets.err (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/webpack/lib/Compiler.js:251:10)
  at hooks.afterEmit.callAsync.err (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/webpack/lib/Compiler.js:357:14)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
  at AsyncSeriesHook.lazyCompileHook (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/tapable/lib/Hook.js:154:20)
  at asyncLib.forEach.err (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/webpack/lib/Compiler.js:354:27)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/neo-async/async.js:2825:7
  at done (/Users/aaaa/Documents/ttttt/aa/aa/node_modules/neo-async/async.js:2861:11)
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/neo-async/async.js:2813:7
  at /Users/aaaa/Documents/ttttt/aa/aa/node_modules/graceful-fs/graceful-fs.js:45:10
  at FSReqWrap.oncomplete (fs.js:141:20)
error Command failed with exit code 1.

```

**Comment by nklayman** [comment]
This appears to be an issue with [electron-builder](https://www.electron.build/) and wine. Delete the `node_modules` folder and try again. Also try with a blank project.

**Comment by d0whc3r** [comment]
You could try with docker using `electronuserland/builder:wine` image it works very good
https://hub.docker.com/r/electronuserland/builder/
https://www.electron.build/multi-platform-build#docker
