### ISSUE TITLE
When webpack is packaged, background.js should be excluded

### ISSUE THREAD

**Issue by qiyaozu** [nklayman/vue-cli-plugin-electron-builder#1465]
File                      Size                                                                    Gzipped

  dist_electron/index.js    801.26 KiB                                                              176.47 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
App threw an error during load
TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (webpack:///./node_modules/bindings/bindings.js?:178:16)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:82:48)
    at eval (webpack:///./node_modules/osx-mouse/index.js?:3:13)
    at Object../node_modules/osx-mouse/index.js (/Users/qiyaozu/yaozu_workspace/vue/hello-vue/dist_electron/index.js:1270:1)
    at __webpack_require__ (/Users/qiyaozu/yaozu_workspace/vue/hello-vue/dist_electron/index.js:20:30)
    at eval (webpack:///./src/background.js?:7:67)
    at Module../src/background.js (/Users/qiyaozu/yaozu_workspace/vue/hello-vue/dist_electron/index.js:1813:1)
    at __webpack_require__ (/Users/qiyaozu/yaozu_workspace/vue/hello-vue/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/Users/qiyaozu/yaozu_workspace/vue/hello-vue/dist_electron/index.js:1824:1)

**Comment by nklayman** [comment]
Please open a new issue that follows the bug report template. I need more information to understand your problem.
