### ISSUE TITLE
Native module error 

### ISSUE THREAD

**Issue by gianlucamazzeo** [nklayman/vue-cli-plugin-electron-builder#1492]
Please can you help me
I'm trying to make two native modules that work with:
ffi-napi, ref-napi,

I've also added in vue.config.js : externals: ['ffi-napi', 'ref-napi']
but the error persist and  returns:
 
INFO Launching Electron ...
App threw an error during load
Error: No native build was found for platform = darwin arch = x64 runtime = electron abi = 87 uv = 1 libc = glibc node = 14.16.0 electron = 12.0.16 webpack = true
    loaded from: / testcerta
    at Function.load.path (webpack: ///./node_modules/node-gyp-build/index.js?: 59: 9)
    at load (webpack: ///./node_modules/node-gyp-build/index.js?: 21: 30)
    at eval (webpack: ///./node_modules/ref-napi/lib/ref.js?: 8: 111)
    at Object ../ node_modules / ref-napi / lib / ref.js (/testcerta/dist_electron/index.js:2365:1)
    at __webpack_require__ (/testcerta/dist_electron/index.js:20:30)
    at eval (webpack: ///./node_modules/ffi-napi/lib/ffi.js?: 7: 13)
    at Object ../ node_modules / ffi-napi / lib / ffi.js (/testcerta/dist_electron/index.js:1171:1)
    at __webpack_require__ (/testcerta/dist_electron/index.js:20:30)
    at eval (webpack: ///./node_modules/sign-sdk/lib/SignSDK.js?: 2: 13)
    at Object ../ node_modules / sign-sdk / lib / SignSDK.js (/testcerta/dist_electron/index.js:2472:1)

_Originally posted by @gianlucamazzeo in https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/861#issuecomment-893321401_

**Comment by gianlucamazzeo** [comment]
fixed in vue.config.js  
pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
        externals: [
          'ffi-napi','ref-napi'
      ]
      }
   }
