### ISSUE TITLE
Attempting to publish via S3 Provider always defaults to Github

### ISSUE THREAD

**Issue by alectrocute** [nklayman/vue-cli-plugin-electron-builder#1544]
Over the past month, something broke and I can no longer publish to S3.

I get the same error & behavior as seen in this closed ticket: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1120 and https://github.com/electron-userland/electron-builder/issues/3139

I'm not utilizing the GitHub Provider anywhere, which makes the error very baffling. This used to work about a month ago when I last released. What changed in the meantime?

In `.env`:

```sh
AWS_ACCESS_KEY_ID=...
AWS_SECRET_ACCESS_KEY=...
VUE_APP_IS_SETAPP=false
```

In `package.json`:

```json
{
  "name": "lift",
  "productName": "Lift",
  "version": "1.0.15",
  "description": "A browser that floats on top",
  "author": "Alec Armbruster <alec@yac.com>",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron:build": "source .env && vue-cli-service electron:build -mw -p never",
    "electron:build-setapp": "source .env && vue-cli-service electron:build -m -p never && node ./build/buildUniversal.js",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps && build-electron-universal-util",
    "postuninstall": "electron-builder install-app-deps",
    "install-widevine-cli": "python3 -m pip install --upgrade castlabs-evs && python3 -m castlabs_evs.account signup",
    "sign-widevine": "python3 -m castlabs_evs.vmp sign-pkg ./dist_electron/mac",
    "build-electron-universal-util": "yarn install --prefix ./build/universal",
    "release": "source .env && vue-cli-service electron:build -mw -p always"
  },
  "main": "background.js",
  "dependencies": {
    "electron-context-menu": "^3.1.1",
    "electron-store": "^8.0.0",
    "electron-updater": "^4.3.9",
    "humanize-url": "^2.1.1",
    "link-preview-js": "^2.1.8",
    "normalize-url": "^6.1.0",
    "tinycolor2": "^1.4.2",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-service": "~4.5.0",
    "electron": "git+https://github.com/castlabs/electron-releases.git#v13.1.6-wvvmp",
    "electron-devtools-installer": "^3.1.0",
    "electron-notarize": "^1.0.0",
    "native-ext-loader": "^2.3.0",
    "vue-cli-plugin-electron-builder": "~2.0.0",
    "vue-template-compiler": "^2.6.11"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

Error: 

```sh
  • signing         file=dist_electron/Lift Setup 1.0.15.exe certificateFile=/Users/alec/Desktop/repos/heliumlift/build/wincert.p12
  • building block map  blockMapFile=dist_electron/Lift Setup 1.0.15.exe.blockmap
InvalidConfigurationError: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (/Users/alec/Desktop/repos/heliumlift/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/Users/alec/Desktop/repos/heliumlift/node_modules/app-builder-lib/src/publish/PublishManager.ts:295:14)
    at PublishManager.getOrCreatePublisher (/Users/alec/Desktop/repos/heliumlift/node_modules/app-builder-lib/src/publish/PublishManager.ts:214:19)
    at PublishManager.scheduleUpload (/Users/alec/Desktop/repos/heliumlift/node_modules/app-builder-lib/src/publish/PublishManager.ts:148:28)
    at EventEmitter.<anonymous> (/Users/alec/Desktop/repos/heliumlift/node_modules/app-builder-lib/src/publish/PublishManager.ts:128:14)
    at EventEmitter.emit (events.js:327:22)
    at Packager.dispatchArtifactCreated (/Users/alec/Desktop/repos/heliumlift/node_modules/app-builder-lib/src/packager.ts:270:23)
    at bluebird_lst_1.default.map.concurrency (/Users/alec/Desktop/repos/heliumlift/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:234:16)
From previous event:
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Object.writeUpdateInfoFiles (/Users/alec/Desktop/repos/heliumlift/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:213:25)
    at PublishManager.awaitTasks (/Users/alec/Desktop/repos/heliumlift/node_modules/app-builder-lib/src/publish/PublishManager.ts:235:11)
    at Object.executeFinally (/Users/alec/Desktop/repos/heliumlift/node_modules/builder-util/src/promise.ts:23:3) {
  code: 'ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION'
}
```

`vue.config.js`:

```js
// vue.config.js

module.exports = {
  pluginOptions: {
    electronBuilder: {

      chainWebpackMainProcess: config => {
        const nodeLoader = "native-ext-loader"

        config.module
          .rule('node')
          .test(/\.node$/)
          .use(nodeLoader)
          .loader(nodeLoader)
          .end()

        config.resolve.extensions.add('.js').add('.node')
      },

      // renderer/dev-related
      preload: 'src/preload.js',
      removeElectronJunk: true,
      nodeIntegration: true,
      customFileProtocol: "myapp://./",

      // electron-builder config
      builderOptions: {
        productName: "App",
        copyright: "© 2021 App Dev",

        // specific to castlabs fork (for widevine cdm)
        electronVersion: "13.1.6-wvvmp",
        electronDownload: {
          mirror: "https://github.com/castlabs/electron-releases/releases/download/v"
        },

        appId: process.env.VUE_APP_IS_SETAPP ? 'com.myapp.app-setapp' : 'com.myapp.app',

        // auto-updater
        publish: process.env.VUE_APP_IS_SETAPP ? undefined : {
          provider: "s3",
          bucket: "app-release",
          region: "us-east-1",
        },

        afterPack: "./build/afterPack.js",
        afterSign: "./build/afterSign.js",

        // darwin (intel and apple silicon)
        mac: {
          entitlements: "./build/entitlements.plist",
          icon: "./build/app.icns",
          category: "public.app-category.productivity",
          artifactName: "${productName}-${arch}-${version}.${ext}",
          target: [{
            target: "dmg",
            arch: ["x64", "arm64"]
          },
          {
            target: "zip",
            arch: ["x64", "arm64"]
          }
          ],
          type: "distribution",
          darkModeSupport: true,
          hardenedRuntime: true,
          extendInfo: {
            LSMultipleInstancesProhibited: true,
            CFBundleURLTypes: {
              NSPrincipalClass: "AtomApplication"
            }
          }
        },

        // windows 10+
        win: {
          target: [{
            target: "nsis",
            arch: ["x64"]
          }],
          icon: "./build/icon.ico",
          publisherName: "App",
          // publish: process.env.VUE_APP_IS_SETAPP ? undefined : {
          //   provider: "s3",
          //   bucket: "app-release"
          // }
        },

      }
    }
  }
}
```

**Comment by alectrocute** [comment]
@nklayman Any help with this one? Thanks.

**Comment by alectrocute** [comment]
Ended up being an issue with my `env` variables. Adding an extra check for `env && env === 'true'` fixed it.
