### ISSUE TITLE
Any idea why scss variables are undefined though they work with non-electron builds?

### ISSUE THREAD

**Issue by elcontraption** [nklayman/vue-cli-plugin-electron-builder#16]
I'm defining scss variables in a file that is imported through`css.loaderOptions.sass.data` in `vue.config.js`:

```js
// vue.config.js

const fs = require('fs')

module.exports = {
  css: {
    loaderOptions: {
      sass: {
        data: fs.readFileSync('src/styles/main.scss', 'utf-8')
      }
    }
  }
}
```

```scss
// src/styles/main.scss

$blue: rgb(0, 111, 186);
$light-blue: rgb(125, 206, 241);
```

I can use those variables just fine in `App.vue` when running `yarn serve` or `yarn build`:
```js
// src/App.vue

<template>
  <div id="app">
  </div>
</template>

<script>
export default {
  name: 'app'
}
</script>

<style lang="scss">
#app {
  background-color: $blue;
}
</style>
```

However, `yarn build:electron` breaks with this:
```
yarn build:electron v1.0.0
$ vue-cli-service build:electron
 59% [1] building modules 75/76 modules 1 active …pp.vue?vue&type=style&index=0&lang=scssDEPRECATION WARNING on line 54, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

[1] Hash: 0cf1583156f0e6feee14b311f3305d675152a863
Version: webpack 4.10.2
Child
    Hash: 0cf1583156f0e6feee14
    Time: 916ms
    Built at: 2018-06-08 10:00:14
          Asset      Size  Chunks             Chunk Names
        main.js  1.88 KiB       0  [emitted]  main
    main.js.map  2.76 KiB       0  [emitted]  main
    [0] external "electron" 42 bytes {0} [built]
    [1] external "url" 42 bytes {0} [built]
    [2] external "path" 42 bytes {0} [built]
    [3] ./src/main/index.js 1.6 KiB {0} [built]
    [4] multi ./src/main/index.js 28 bytes {0} [built]
Child
    Hash: b311f3305d675152a863
    Time: 4893ms
    Built at: 2018-06-08 10:00:18
     4 assets
     [9] ./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss 1020 bytes {0} [built] [failed] [1 error]
    [14] external "vuex" 42 bytes {0} [built]
    [26] ./src/main.js + 18 modules 9.19 KiB {0} [built]
         | ./src/main.js 251 bytes [built]
         | ./src/store/index.js 226 bytes [built]
         | ./src/App.vue 504 bytes [built]
         | ./src/store/modules/attract.js 753 bytes [built]
         | ./src/App.vue?vue&type=script&lang=js 346 bytes [built]
         | ./src/App.vue?vue&type=template&id=78c88d74 194 bytes [built]
         | ./node_modules/babel-loader/lib??ref--0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js 848 bytes [built]
         | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=template&id=78c88d74 241 bytes [built]
         |     + 11 hidden modules
    [27] ./src/App.vue?vue&type=style&index=0&lang=scss 646 bytes {0} [built]
    [57] multi ./node_modules/electron-webpack/vue-renderer-entry.js ./src/main.js 40 bytes {0} [built]
        + 53 hidden modules

    ERROR in ./src/App.vue?vue&type=style&index=0&lang=scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss)
    Module build failed: ModuleBuildError: Module build failed:
      background-color: $blue;
                       ^
          Undefined variable: "$blue".
          in /[path/to]/src/App.vue (line 59, column 21)
        at runLoaders (/[path/to]/node_modules/webpack/lib/NormalModule.js:259:20)
        at /[path/to]/node_modules/loader-runner/lib/LoaderRunner.js:364:11
        at /[path/to]/node_modules/loader-runner/lib/LoaderRunner.js:230:18
        at context.callback (/[path/to]/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (/[path/to]/node_modules/sass-loader/lib/loader.js:67:13)
        at Object.done [as callback] (/[path/to]/node_modules/neo-async/async.js:7974:18)
        at options.error (/[path/to]/node_modules/node-sass/lib/index.js:294:32)
     @ ./src/App.vue?vue&type=style&index=0&lang=scss 1:0-314 1:330-333 1:335-646 1:335-646
     @ ./src/App.vue
     @ ./src/main.js
     @ multi ./node_modules/electron-webpack/vue-renderer-entry.js ./src/main.js
    Child html-webpack-plugin for "index.html":
         1 asset
        [0] ./node_modules/html-loader/dist/cjs.js?minimize=false!./dist/.renderer-index-template.html 260 bytes {0} [built]
    Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/sass-loader/lib/loader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!src/App.vue?vue&type=style&index=0&lang=scss:
        [0] ./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss 208 bytes {0} [built] [failed] [1 error]

        ERROR in ./src/App.vue?vue&type=style&index=0&lang=scss (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss)
        Module build failed:
          background-color: $blue;
                           ^
              Undefined variable: "$blue".
              in /[path/to]/src/App.vue (line 59, column 21)
    Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/sass-loader/lib/loader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!src/components/AttractOverlay.vue?vue&type=style&index=0&id=0eb1c98a&scoped=true&lang=scss:
        [0] ./src/assets/attract-overlay-wave.svg 465 bytes {0} [built]
            + 3 hidden modules
    Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!src/components/SvgDefs.vue?vue&type=style&index=0&lang=css:
           2 modules
 ERROR  Error: electron-webpack exited with code 2.
Error: electron-webpack exited with code 2.
    at ChildProcess.child.on.code (/[path/to]/node_modules/vue-cli-plugin-electron-builder/index.js:40:20)
    at ChildProcess.emit (events.js:132:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
error Command failed with exit code 1.
```

**Comment by nklayman** [comment]
Follow the instructions [here](https://webpack.electron.build/add-ons#sassscss) to add sass/scss support, it should build successfully then. You will have to use a separate loader for the variables like [this](https://github.com/nordnet/sass-variable-loader). Please close the issue and mention how you got the variables working if you do. Thanks.

**Comment by nklayman** [comment]
In v1.0.0 (two weeks away), you will be able to use variables the normal way, as vue.config.js will be used.

**Comment by nklayman** [comment]
I just released the first v1.0.0 alpha! Go ahead and try it again with the new version and let me know if it works. Thanks.

**Comment by elcontraption** [comment]
Nice, now it works as set up at the top of this thread. Thanks!

**Comment by elcontraption** [comment]
Thought I had it working but I spoke too soon. Currently stuck on #24.

**Comment by nklayman** [comment]
What os are you using?

**Comment by nklayman** [comment]
Please follow the instructions on this [issue comment](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/24#issuecomment-398149671). Thanks!

**Comment by Jack-Barry** [comment]
I hit this issue when trying to reorganize the `src` directory of our app and placed `styles` into a subfolder named `renderer`. This breaks the reference that Vuetify uses. After a lot of contact between my head and desk, I found out the secret sauce is this in `vue.config.js`:

```js
const importVariablesScss = `@import "~@/renderer/styles/variables.scss"`

module.exports = {
  css: {
    loaderOptions: {
      sass: { additionalData: importVariablesScss }, // No semi-colon
      scss: { additionalData: `${importVariablesScss};` } // Semi-colon
    }
  }
  // Other stuff
}
```

I guess they both have to be there in order for it to work. (I was under the assumption it would only need to be one or the other for some reason 🤷‍♂️) If either is missing it causes issues though. Hope this helps anybody else trying to do something similar
