### ISSUE TITLE
3.0.0-alpha.0 Error: Application entry file "background.js". Seems like a wrong configuration.

### ISSUE THREAD

**Issue by AndreiSoroka** [nklayman/vue-cli-plugin-electron-builder#1637]
Hello! I migrated to 3.0.0-alpha.0
```json
{
"electron": "^13.6.3",
"vue-cli-plugin-electron-builder": "^3.0.0-alpha.0"
}
```

**Describe the bug**
When I call `vue-cli-service electron:build -mw;` I got the error:
```
Error: Application entry file "background.js" in the "/Users/andreisoroka/git/.../dist_electron/mac/App.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at MacPackager.checkFileInPackage (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/platformPackager.ts:501:7)
    at MacPackager.sanityCheckPackage (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/platformPackager.ts:549:5)
    at MacPackager.doPack (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/platformPackager.ts:310:5)
    at MacPackager.pack (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/macPackager.ts:177:7)
    at Packager.doBuild (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/andreisoroka/git/.../node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/andreisoroka/git/.../node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/andreisoroka/git/.../node_modules/builder-util/src/promise.ts:12:14)

```

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 ```javascript
const StyleLintPlugin = require('stylelint-webpack-plugin');
const SentryCliPlugin = require('@sentry/webpack-plugin');
const packageJson = require('./package.json');

const plugins = [
  new StyleLintPlugin({
    files: ['src/**/*.{vue,scss}'],
  }),
  ...(process.env.NODE_ENV === 'production'
    ? [
      new SentryCliPlugin({
        include: '.',
        ignoreFile: '.sentrycliignore',
        ignore: [
          'node_modules',
          'webpack.config.js',
          'vue.config.js',
          'dist_electron',
          '.husky',
          'build',
          'tests',
        ],
        configFile: 'sentry.properties',
        authToken: process.env.SENTRY_AUTH_TOKEN,
        release: packageJson.version,
        project: packageJson.name,
        org: process.env.SENTRY_ORG,
      }),
    ]
    : []
  ),
];

module.exports = {
  pages: {
    index: 'src/pageMain.js',
    templateWindow: 'src/pageTemplate.js',
  },
  configureWebpack: {
    plugins,
  },

  chainWebpack(config) {
    config.resolve.symlinks(false);

    config.module
      .rule('i18n')
      .resourceQuery(/blockType=i18n/)
      .type('javascript/auto')
      .use('i18n')
      .loader('@kazupon/vue-i18n-loader')
      .end();
  },

  pluginOptions: {
    i18n: {
      locale: 'en',
      fallbackLocale: 'en',
      localeDir: 'locales',
      enableInSFC: false,
    },
  },
};

```
 - terminal output from running `vue info`:
 ```
Environment Info:

  System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.12 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.2
  npmPackages:
    @kazupon/vue-i18n-loader: ^0.3.0 => 0.3.0 
    @storybook/vue: ^6.4.9 => 6.4.9 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.1.1 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.15 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.15 
    @vue/cli-plugin-babel: ^4.5.15 => 4.5.15 
    @vue/cli-plugin-eslint: ^4.5.15 => 4.5.15 
    @vue/cli-plugin-router: ^4.5.15 => 4.5.15 
    @vue/cli-plugin-unit-mocha: ^4.5.15 => 4.5.15 
    @vue/cli-plugin-vuex: ^4.5.15 => 4.5.15 
    @vue/cli-service: ^4.5.15 => 4.5.15 
    @vue/cli-shared-utils:  4.5.13 (4.5.15, 5.0.0-rc.1)
    @vue/compiler-core:  3.2.26 
    @vue/compiler-dom:  3.2.26 
    @vue/compiler-sfc:  3.2.26 
    @vue/compiler-ssr:  3.2.26 
    @vue/component-compiler-utils:  3.3.0 
    @vue/composition-api: ^1.4.3 => 1.4.3 
    @vue/eslint-config-airbnb: ^5.3.0 => 5.3.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity-transform:  3.2.26 
    @vue/shared:  3.2.26 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.3.0 
    bootstrap-vue: ^2.21.2 => 2.21.2 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    portal-vue:  2.1.7 
    primevue: ^2.8.0 => 2.8.0 
    vue: ^2.6.14 => 2.6.14 
    vue-cli-plugin-electron-builder: ^3.0.0-alpha.0 => 3.0.0-alpha.0 
    vue-cli-plugin-i18n: ^1.0.1 => 1.0.1 
    vue-cli-plugin-storybook: ^2.1.0 => 2.1.0 
    vue-cli-plugin-svg-sprite: ~1.1.0 => 1.1.0 
    vue-docgen-api:  4.43.1 
    vue-docgen-loader:  1.5.0 
    vue-esc: ^3.0.1 => 3.0.1 
    vue-eslint-parser:  7.3.0 
    vue-functional-data-merge:  3.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.26.8 => 8.26.8 
    vue-i18n-extract:  1.0.2 
    vue-inbrowser-compiler-utils:  4.43.1 
    vue-loader:  15.9.8 (16.8.3)
    vue-moment: ^4.1.0 => 4.1.0 
    vue-router: ^3.5.3 => 3.5.3 
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.14 => 2.6.14 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.6.2 => 3.6.2 
    vuex-multi-tab-state: ^1.0.17 => 1.0.17 
    vuex-persistedstate: ^3.2.1 => 3.2.1 
  npmGlobalPackages:
    @vue/cli: 4.5.14
```

package.json
```json
{
 "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "VUE_APP_TEST=E2E mocha -r esm -b ./tests/e2e/",
    "test:e2e:dev": "VUE_APP_TEST=E2E VUE_APP_TEST_DEV=1 mocha -r esm -b ./tests/e2e/",
    "lint": "vue-cli-service lint",
    "lint:fix": "vue-cli-service lint --fix",
    "lint:style": "stylelint ./src/**/*.{vue,scss} --fix",
    "electron:build": "vue-cli-service electron:build -mw; npm run rebuild:after-windows-build",
    "electron:build:mac": "vue-cli-service electron:build --mac",
    "electron:build:windows": "vue-cli-service electron:build --win; npm run rebuild:after-windows-build",
    "electron:generate-icons": "electron-icon-builder --input=./public/icon.png --output=build --flatten",
    "electron:serve": "vue-cli-service electron:serve",
    "i18n:report": "vue-cli-service i18n:report --src './src/**/*.?(js|vue)' --locales './src/locales/**/*.json'",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "storybook:build": "STORYBOOK_ENABLED=1 vue-cli-service storybook:build -c config/storybook",
    "storybook:serve": "STORYBOOK_ENABLED=1 vue-cli-service storybook:serve -p 6006 -c config/storybook",
    "rebuild": "npm rebuild --runtime=electron --target=13.1.9 --disturl=https://atom.io/download/atom-shell --abi=89",
    "rebuild:after-windows-build": " cd ./src/addons; npm run build",
    "rebuild:deprecated-example": "electron-rebuild -f -m ./src/addons",
    "prepare": "husky install"
  },
  "main": "background.js",
  "dependencies": {
    "@sentry/browser": "^6.16.1",
    "@sentry/integrations": "^6.16.1",
    "@vue/composition-api": "^1.4.3",
    "addons-cpp": "file:src/addons",
    "bootstrap": "^4.6.1",
    "bootstrap-vue": "^2.21.2",
    "chart.js": "^3.7.0",
    "countryinfo": "^1.0.5",
    "electron": "^13.6.3",
    "idb": "^7.0.0",
    "is-eu-member": "^1.0.6",
    "js-bbcode-parser": "^3.0.5",
    "js-sha512": "^0.8.0",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "node-email-validator": "^1.1.1",
    "node-fetch": "^2.6.6",
    "node-html-parser": "^1.4.9",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primevue": "^2.8.0",
    "server-accepts-email": "^1.11.1",
    "string-similarity": "^4.0.4",
    "universal-analytics": "^0.4.23",
    "uuid": "^8.3.2",
    "vue": "^2.6.14",
    "vue-esc": "^3.0.1",
    "vue-i18n": "^8.26.8",
    "vue-moment": "^4.1.0",
    "vue-router": "^3.5.3",
    "vuex": "^3.6.2",
    "vuex-multi-tab-state": "^1.0.17",
    "vuex-persistedstate": "^3.2.1"
  },
  "devDependencies": {
    "@babel/plugin-proposal-optional-chaining": "^7.16.7",
    "@kazupon/vue-i18n-loader": "^0.3.0",
    "@sentry/webpack-plugin": "^1.18.3",
    "@storybook/addon-actions": "^6.4.9",
    "@storybook/addon-knobs": "^6.4.0",
    "@storybook/addon-links": "^6.4.9",
    "@storybook/addon-notes": "^5.3.21",
    "@storybook/vue": "^6.4.9",
    "@vue/cli-plugin-babel": "^4.5.15",
    "@vue/cli-plugin-eslint": "^4.5.15",
    "@vue/cli-plugin-router": "^4.5.15",
    "@vue/cli-plugin-unit-mocha": "^4.5.15",
    "@vue/cli-plugin-vuex": "^4.5.15",
    "@vue/cli-service": "^4.5.15",
    "@vue/eslint-config-airbnb": "^5.3.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-eslint": "^10.1.0",
    "chai": "^4.3.4",
    "electron-devtools-installer": "^3.2.0",
    "electron-icon-builder": "^2.0.1",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-vue": "^6.2.2",
    "husky": "^7.0.4",
    "node-addon-api": "^4.2.0",
    "sass": "^1.45.2",
    "sass-loader": "^8.0.0",
    "spectron": "11.0.0",
    "stylelint": "^13.13.1",
    "stylelint-config-recommended-scss": "^4.3.0",
    "stylelint-scss": "^3.21.0",
    "stylelint-webpack-plugin": "^2.3.1",
    "vue-cli-plugin-electron-builder": "^3.0.0-alpha.0",
    "vue-cli-plugin-i18n": "^1.0.1",
    "vue-cli-plugin-storybook": "^2.1.0",
    "vue-cli-plugin-svg-sprite": "~1.1.0",
    "vue-template-compiler": "^2.6.14"
  }
}
```

**Comment by nklayman** [comment]
Remove the `main` field from your `package.json` to fix that. I think I'll add a feature that will check for the main field and display a warning since v2 added it by default and v3 won't work with it.

**Comment by AndreiSoroka** [comment]
it's working, thanks

**Comment by ericlogic** [comment]
I have 2 projects, both are using 3.0.0-alpha.4. One works fine while the other has same issue. What causes this?

**Comment by IH-Priyam** [comment]
When I removed the main: "background.js" from my package.json, I get a similar error related to index.jx. 

Error: Error: Application entry file "index.js" in the "/home/priyam/application-improvment-UserMode/dist_electron/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.

What is the root cause of this issue? How do I debug this?
