### ISSUE TITLE
Error: Application entry file "background.js" in the "/Users/xyy/Documents/yxrt/electron-vue/dist_electron/mac/electron-vue.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.

### ISSUE THREAD

**Issue by xiongyayun428** [nklayman/vue-cli-plugin-electron-builder#1674]
INFO  Building app with electron-builder:
  • electron-builder  version=23.0.0 os=21.3.0
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=17.0.1 appOutDir=dist_electron/mac
Error: Application entry file "background.js" in the "/Users/xyy/Documents/yxrt/electron-vue/dist_electron/mac/electron-vue.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at MacPackager.checkFileInPackage (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:503:7)
    at MacPackager.sanityCheckPackage (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:551:5)
    at MacPackager.doPack (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
    at MacPackager.pack (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/macPackager.ts:179:7)
    at Packager.doBuild (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/xyy/Documents/yxrt/electron-vue/node_modules/vue-cli-plugin-electron-builder/node_modules/builder-util/src/promise.ts:12:14)

**Comment by nklayman** [comment]
Please open an issue that follows the bug report template. I need more information to debug this.
