### ISSUE TITLE
Errors running `electron:serve` in a monorepo

### ISSUE THREAD

**Issue by algil** [nklayman/vue-cli-plugin-electron-builder#170]
**Describe the bug**
In a monorepo with lerna and yarn workspaces (where node_modules are in the root directory) errors appears when run `electron:serve` script. Anyway, the app is launched and all is working as expected.

```
Error: Could not find a package.json for module lodash
    at Object.keys.filter.dep (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/lib/webpackConfig.js:72:15)
    at Array.filter (<anonymous>)
    at getExternals (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/lib/webpackConfig.js:57:57)
    at chainWebpack (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/lib/webpackConfig.js:9:22)
    at api.chainWebpack (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/index.js:42:5)
    at webpackChainFns.forEach.fn (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:225:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:225:26)
    at Service.resolveWebpackConfig (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:229:48)
    at PluginAPI.resolveWebpackConfig (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/PluginAPI.js:115:25)
    at serve (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/commands/serve.js:48:31)
    at Service.run (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:219:12)
    at api.registerCommand (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/index.js:212:40)
    at Service.run (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:219:12)
    at Object.<anonymous> (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
Error: Could not find a package.json for module vue
    at Object.keys.filter.dep (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/lib/webpackConfig.js:72:15)
    at Array.filter (<anonymous>)
    at getExternals (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/lib/webpackConfig.js:57:57)
    at chainWebpack (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/lib/webpackConfig.js:9:22)
    at api.chainWebpack (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/index.js:42:5)
    at webpackChainFns.forEach.fn (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:225:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:225:26)
    at Service.resolveWebpackConfig (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:229:48)
    at PluginAPI.resolveWebpackConfig (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/PluginAPI.js:115:25)
    at serve (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/commands/serve.js:48:31)
    at Service.run (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:219:12)
    at api.registerCommand (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/vue-cli-plugin-electron-builder/index.js:212:40)
    at Service.run (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/lib/Service.js:219:12)
    at Object.<anonymous> (/Users/algil/dev/demos/electron/vue-electron-monorepo/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
...
```

**To Reproduce**
- Clone this repo https://github.com/algil/vue-electron-monorepo
- Run `yarn` in the root folder
- Run `npx lerna bootstrap` in the root folder
- Go to `packages/desktop` module and run `yarn electron:serve`
- In build process the errors appear

**Expected behavior**
Any error should be shown in the console

**Environment (please complete the following information):**
 - OS and version: Mac OSX 10.14.2
 - node version: 11.2.0
 - npm version: 6.5.0
 - yarn version (if used): 1.12.3
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.10
 - electron version: 3.0.13
 - other vue plugins used: None
 - custom config for vcp-electron-builder: None
 - (if possible) link to your repo: https://github.com/algil/vue-electron-monorepo

**Additional context**
Using Typescript

**Comment by nklayman** [comment]
Use nodeModulesPath:

```javascript
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      // If you are using Yarn Workspaces, you may have multiple node_modules folders
      // List them all here so that VCP Electron Builder can find them
      nodeModulesPath: ['../../node_modules', './node_modules']
    }
  }
}
```

**Comment by algil** [comment]
Thanks! Now it works fine!

**Comment by davidmoshal** [comment]
@nklayman  that's brilliant, thanks!   
and... that advice should be in the readme for this project!
