### ISSUE TITLE
Error: Cannot find module 'fs/promises' Require stack:

### ISSUE THREAD

**Issue by kurohoan** [nklayman/vue-cli-plugin-electron-builder#1722]
```
windows 10
node v16.14.0
yarn v1.22.18
vue-cli-plugin-electron-builder v2.1.1

```

 When "yarn electron:serve" is executed in the above environment, the following error message is displayed.

```
INFO  Launching Electron...
App threw an error during load
Error: Cannot find module 'fs/promises'
Require stack:
- C:\Users\username\XXXX\dist_electron\index.js
- C:\Users\username\XXXX\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack:///external_%22fs/promises%22?:1:18)
    at Object.fs/promises (C:\Users\username\XXXX\dist_electron\index.js:8173:1)
    at __webpack_require__ (C:\Users\username\XXXX\dist_electron\index.js:20:30)
    at eval (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:8:20)
```

**Comment by jasonwwl** [comment]
+1

**Comment by cp-sumi-k** [comment]
Have the same problem with the same configurations.

**Comment by klren0312** [comment]
try to add this to `vue.config.js`

```js
module.exports = defineConfig({
  pluginOptions: {
    electronBuilder: {
      externals: ['fs/promises'],
    }
  }
})
```

**Comment by Happyrain67** [comment]
See nodeIntegration configuration.

FS is not authorized by Electron in rendered files, only on background process.

And... upgrade your version of vue-cli-plugin-electron-builder with v3 guys ;)

**Comment by IceApriler** [comment]
> ```js
> electronBuilder
> ```

Have not solved the problem.
