### ISSUE TITLE
Question: How to reference local resources use path.join

### ISSUE THREAD

**Issue by Jiiiiiin** [nklayman/vue-cli-plugin-electron-builder#180]
## I encounter an error when I used the interface to find the next resource file for the project. like this:

in background.js i include a module:

![](https://ws3.sinaimg.cn/large/006tNc79gy1fz1ihnbuoxj320y0u0go4.jpg)

the tray.js
```js
const path = require('path')
const { ipcMain, app, Menu, Tray } = require('electron')

let appIcon = null

const _creatAppTray = function () {
  const iconName = process.platform === 'win32' ? 'windows-icon.png' : 'iconTemplate.png'
  const iconPath = path.join(__dirname, iconName)
  appIcon = new Tray(iconPath)

  const contextMenu = Menu.buildFromTemplate([{
    label: '移除',
    click: () => {
      event.sender.send('tray-removed')
    }
  }])

  appIcon.setToolTip('在托盘中的 Electron 示例.')
  appIcon.setContextMenu(contextMenu)
}

_creatAppTray()
```

the problem:

```bash
 INFO  Launching Electron...
App threw an error during load
TypeError: Error processing argument at index 0, conversion failure from /Users/jiiiiiin/Documents/GitHub/ynrcc-emobilebank-desktopapp/dist_electron/iconTemplate.png
    at _creatAppTray (webpack:///./src/main-process/native-ui/tray/tray.js?:9:13)
    at eval (webpack:///./src/main-process/native-ui/tray/tray.js?:22:1)
    at Object../src/main-process/native-ui/tray/tray.js (/Users/jiiiiiin/Documents/GitHub/ynrcc-emobilebank-desktopapp/dist_electron/index.js:1450:1)
    at __webpack_require__ (/Users/jiiiiiin/Documents/GitHub/ynrcc-emobilebank-desktopapp/dist_electron/index.js:20:30)
    at webpackContext (webpack:///./src_sync_^.*\/native\-ui\/tray\/tray\.js$?:8:9)
    at requireModule (webpack:///./src/background-util.js?:5:84)
    at eval (webpack:///./src/background.js?:14:71)
    at Module../src/background.js (/Users/jiiiiiin/Documents/GitHub/ynrcc-emobilebank-desktopapp/dist_electron/index.js:1417:1)
    at __webpack_require__ (/Users/jiiiiiin/Documents/GitHub/ynrcc-emobilebank-desktopapp/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
```

my work env:

 - OS and version: latest
 - node version: latest
 - npm version:latest
 - vue-cli-plugin-electron-builder version : latest
 - electron version: ^3.0.0

**Comment by nklayman** [comment]
Glad that you could figure it out!
