### ISSUE TITLE
loaderContext.getOptions is not a function

### ISSUE THREAD

**Issue by IceApriler** [nklayman/vue-cli-plugin-electron-builder#1813]
I used vue-cli to initialize a vue3 project and then executed `vue add electron-builder`.

Run `npm run serve` was successfully.
Run `npm run electron:serve` was faild.

```bash
 error  in ./src/background.ts

Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/xxx/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/xxx/node_modules/ts-loader/dist/index.js:14:21)

 @ multi ./src/background.ts

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx@0.1.0 electron:serve: `vue-cli-service electron:serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxx@0.1.0 electron:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by MatthijsBurgh** [comment]
Vue3 is not yet supported

**Comment by IceApriler** [comment]
Ok, thanks. I see.

**Comment by IceApriler** [comment]
I run `vue add electron-builder@alpha`. 

It's working properly. Perfect!

**Comment by MatthijsBurgh** [comment]
The alpha does support it. but remember it is an alpha
