### ISSUE TITLE
custom keyword definition is invalid

### ISSUE THREAD

**Issue by jyrula** [nklayman/vue-cli-plugin-electron-builder#187]
**Describe the bug**
Running electron:serve or test:unit fails with the following error log:
```
$ vue-cli-service test:unit
D:\code\js\demo4\node_modules\ajv\lib\keyword.js:65
      throw new Error('custom keyword definition is invalid: '  + this.errorsText(validateDefinition.errors));
      ^

Error: custom keyword definition is invalid: data/errors should be boolean
    at Ajv.addKeyword (D:\code\js\demo4\node_modules\ajv\lib\keyword.js:65:13)
    at module.exports (D:\code\js\demo4\node_modules\ajv-errors\index.js:10:7)
    at Object.<anonymous> (D:\code\js\demo4\node_modules\terser-webpack-plugin\node_modules\schema-utils\src\validateOptions.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**To Reproduce**
Create a vue project with custom preset with the following configurations:
- Babel
- Linter (ESLint + Standard config)
- CSS pre-processors 
- Unit Testing (Jest)
- Use config files

**Expected behavior**
Scripts should run without any error after installing the plugin.

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: 10.11.0
 - npm version: 6.4.1
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.11
 - electron version: 4.0.4

**Comment by jyrula** [comment]
sorry, turns out this issue is a webpack issue. webpack/webpack#8768

**Comment by nklayman** [comment]
Thanks for reporting it anyway, that error was really confusing me on a different project.👍
