### ISSUE TITLE
electron-build Cannot find module

### ISSUE THREAD

**Issue by NidhoogJX** [nklayman/vue-cli-plugin-electron-builder#1886]
**Describe the bug**
I have a project that needs to introduce the ffi napi module to use the dll dynamic link library
This module works well in the development preview, but when I package it as a win32 exe program, an error will be reported
```
Cannot find module 'ffi-napi'

**[2022-11-13 21:28:23.316] [debug] [
  "Error: Cannot find module 'ffi-napi'\n" +
    'Require stack:\n' +
    '- electron/js2c/renderer_init\n' +
    '    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)\n' +
    '    at Function.o._resolveFilename (electron/js2c/renderer_init.js:33:1118)\n' +
    '    at Module._load (internal/modules/cjs/loader.js:732:27)\n' +
    '    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)\n' +
    '    at Function.o._load (electron/js2c/renderer_init.js:33:379)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:959:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
    '    at Object.54dc (app://./js/app.212846b3.js:1:4729)\n' +
    '    at u (app://./js/app.212846b3.js:1:855)\n' +
    '    at Object.e307 (app://./js/app.212846b3.js:1:9795)'
]**
```

When I introduced the module, I was told that the C native code of this module needs to be obtained at runtime and added in the configuration
`externals: ['ffi-napi', 'ref-napi'],`

When I introduced the module, I was told that the C native code of this module needs to be obtained at runtime and added in the configuration to prevent it from being packaged into the bundle by the webpack. However, I still can't work normally. I don't know whether it is an electric problem, a ffi napi problem, or a vue cil problem. I don't know enough about the packaging process. I want to get help. I have queried many articles, but none of them are like me

Here is my profile package.json

```json
{
  "name": "vue3-electron",
  "version": "0.1.0",
  "private": true,
  "start": "chcp 65001 && electron .",
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "asar": "^3.2.0",
    "axios": "^0.27.2",
    "core-js": "^3.6.5",
    "crypto-js": "^4.1.1",
    "electron-log": "^4.4.8",
    "electron-notarize": "^1.2.1",
    "ffi-napi": "^4.0.3",
    "node-gyp": "^9.3.0",
    "ref-array-napi": "^1.2.2",
    "ref-napi": "^3.0.3",
    "ref-struct-napi": "^1.1.1",
    "vant": "^3.4.9",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.15",
    "@vue/cli-plugin-router": "~4.5.15",
    "@vue/cli-plugin-vuex": "~4.5.15",
    "@vue/cli-service": "~4.5.15",
    "@vue/compiler-sfc": "^3.0.0",
    "electron": "^13.0.0",
    "electron-devtools-installer": "^3.1.0",
    "less": "^3.0.4",
    "less-loader": "^5.0.0",
    "md5": "^2.3.0",
    "vue-cli-plugin-electron-builder": "~2.1.1"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ],
  "description": "一个说明",
  "author": "lcl"
}
```

vue.config.js
```js
module.exports = {
  publicPath: process.env.NODE_ENV === 'production' ? './' : '/',
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      //Because these two modules contain native C code, they should be retrieved at runtime, rather than being packaged into bundles by webpacks
      externals: ['ffi-napi', 'ref-napi'],
      builderOptions: {
        productName: 'demo',
        afterSign: './src/notarize.js',
        appId: 'com.xiaotianyuan.dhspeed',
        productName: 'dhspeed', //Project name, which is also the name of the generated installation file
        copyright: 'Copyright  2022',//Copyright Information
        icon: './public/favicon.ico', 
        files: ['./**/*', '!node_modules'],
        extraFiles: [
          './server',
        ],
        directories: {
          output: './app_dist',
        },
        extraResources: [
          {
          
            from: './dist_electron/dll/',
            to: './',
          },
        ],
        win: {
       
          icon: './public/favicon.ico', 
          requestedExecutionLevel: 'requireAdministrator', 
          target: [
            {
              target: 'nsis', 
              arch: [
                'x64', // 64位
                // 'ia32',
              ],
            },
          ],
        },
        mac: {
          target: [
        
            'dmg',
          ],
          hardenedRuntime: true,
          gatekeeperAssess: false,
          entitlements: 'electron-builder/entitlements.plist', 
          entitlementsInherit: 'electron-builder/entitlements.plist',
          provisioningProfile:
            'electron-builder/comalibabaslobs.provisionprofile',
        },
        dmg: {
          sign: false,
          contents: [
         
            {
              x: 112,
              y: 165,
            },
            {
              type: 'link',
              path: '/Applications',
              x: 396,
              y: 165,
            },
          ],
        },
        nsis: {
          oneClick: false, 
          allowElevation: true,
          allowToChangeInstallationDirectory: true, 
          installerIcon: './favicon.ico',
          uninstallerIcon: './favicon.ico', 
          installerHeaderIcon: './favicon.ico', 
          createDesktopShortcut: true,
          createStartMenuShortcut: true,
          shortcutName: 'mzDemo', 
        },
      },
    },
  },
  // devServer: {
  //   proxy: {
  //     "/api": {
  //       target: "https://fast.kkspeed.com/",
  //       changeOrigin: true,
  //       pathRewrite: {
  //         "^/api": "",
  //       },
  //     },
  //   },
  // },
}
```

This is where I wrote the tool class to introduce modules joke.dll

```js
import logger from './log'
var iserror = false
try{
    const ffi = require('ffi-napi')
    var ref = require('ref-napi')
}
catch(e){
    iserror = true
    console.log('Failed to import the ffi napi module after packaging. Details are as follows:')
    console.log(e)
}


const path = require('path')
let { arch } = process // x64


// let dllFilePath = path.resolve('resources/joker.dll')
let dllFilePath = path.resolve('dll/joker.dll')

    const jokerdll = new ffi.Library(dllFilePath, {
       
   
    })
}
```

**Comment by JunzheFan** [comment]
Did you try removing those two packages in the  externals: [] ? Accroding to webpack doc: **Instead, the created bundle relies on that dependency to be present in the consumer's (any end-user application) environment**,   can you assure the end-users' machines will have those dependency pre-installed ?

**Comment by AutismPatient** [comment]
![image](https://user-images.githubusercontent.com/37021551/217180120-d2c1f23d-63d6-4d4a-9596-cf2ab3fbde12.png)

**Comment by AutismPatient** [comment]
> ![图像](https://user-images.githubusercontent.com/37021551/217180120-d2c1f23d-63d6-4d4a-9596-cf2ab3fbde12.png)

Anybody answer me？

**Comment by MatthijsBurgh** [comment]
@AutismPatient Please open your own issue. Where you explain what you are doing and what is not working. Also provide a reproduceable example. I am deleting your post here.

**Comment by MatthijsBurgh** [comment]
@NidhoogJX please respond on whether the solution of @JunzheFan works for you. Otherwise closing this issue.
