### ISSUE TITLE
ERROR: You are using an outdated version of NPM.

### ISSUE THREAD

**Issue by oase473** [nklayman/vue-cli-plugin-electron-builder#1992]
**Describe the bug**
ERROR: You are using an outdated version of NPM.

It does not support some core functionalities of Vue CLI.

Please upgrade your NPM version.

**To Reproduce**
```
$ nvm use 20 
// Works.

$ vue add electron-builder

📦  Installing vue-cli-plugin-electron-builder...

 ERROR  Error: You are using an outdated version of NPM.
        It does not support some core functionalities of Vue CLI.
        Please upgrade your NPM version.
Error: You are using an outdated version of NPM.
It does not support some core functionalities of Vue CLI.
Please upgrade your NPM version.
    at new PackageManager (C:\Users\pybt07\.nvm\versions\node\v20.10.0\bin\node_modules\@vue\cli\lib\util\ProjectPackageManager.js:129:15)
    at add (C:\Users\pybt07\.nvm\versions\node\v20.10.0\bin\node_modules\@vue\cli\lib\add.js:50:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Expected behavior**
I expected the package to be installed properly.

**Screenshots**

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: IDK
 - (if possible) link to your repo: I don't use a public repo.
 - terminal output from running `vue info`:
 ```
$ vue info

Environment Info:

  System:
    OS: Windows 11 10.0.22000
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-12850HX
  Binaries:
    Node: 20.10.0 - ~\.nvm\versions\node\v20.10.0\bin\node.EXE
    Yarn: Not Found
    npm: 10.3.0 - ~\.nvm\versions\node\v20.10.0\bin\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.2600.0), Chromium (120.0.2210.133)
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.1 => 0.1.1 
    @kazupon/vue-i18n-loader: ^0.3.0 => 0.3.0 
    babel-helper-vue-jsx-merge-props: ^2.0.3 => 2.0.3 
    babel-plugin-transform-vue-jsx: ^3.5.0 => 3.7.0 
    vue: ^2.5.2 => 2.5.17 (2.5.16)
    vue-cli:  1.0.0 
    vue-hot-reload-api:  2.3.1 
    vue-i18n: ^8.14.1 => 8.14.1 
    vue-loader: ^13.3.0 => 13.7.3 
    vue-router: ^3.0.1 => 3.0.1 
    vue-style-loader: ^3.0.3 => 3.1.2 
    vue-template-compiler: ^2.5.2 => 2.5.17 
    vue-template-es2015-compiler:  1.8.1 
    vue-worker: ^1.2.1 => 1.2.1 
    vue2-highcharts: ^1.1.9 => 1.2.5 
    vuedraggable: ^2.24.1 => 2.24.1 
    vuex: ^3.0.1 => 3.0.1 
  npmGlobalPackages:
    @vue/cli: Not Found
 ```

**Additional context**
I'm working on ald old project from former colleagues based on vue2. The apparent vue-cli package is version 1.0.0.

**Comment by biangz** [comment]
Hi, has it been resolved? T.T
