### ISSUE TITLE
Cannot install electron-builder due to impossible node version conflicts

### ISSUE THREAD

**Issue by halkony** [nklayman/vue-cli-plugin-electron-builder#2002]
**Describe the bug**
When installing the package with `vue add electron-builder` with Node 18.20, I receive this error message
```
📦  Installing vue-cli-plugin-electron-builder...

yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
 ERROR  Error: command failed: yarn add vue-cli-plugin-electron-builder -D --tilde
Error: command failed: yarn add vue-cli-plugin-electron-builder -D --tilde
    at ChildProcess.<anonymous> (C:\Users\halkony\.bun\install\global\node_modules\@vue\cli\lib\util\executeCommand.js:138:16)
    at ChildProcess.emit (node:events:517:28)
    at cp.emit (C:\Users\halkony\.bun\install\global\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1098:16)
```

I switched my Node to 17.9 using nvm, and get a similar error.
```

📦  Installing vue-cli-plugin-electron-builder...

yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @vitejs/plugin-vue@5.2.1: The engine "node" is incompatible with this module. Expected version "^18.0.0 || >=20.0.0". Got "17.9.1"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Found incompatible module.
 ERROR  Error: command failed: yarn add vue-cli-plugin-electron-builder -D --tilde
Error: command failed: yarn add vue-cli-plugin-electron-builder -D --tilde
    at ChildProcess.<anonymous> (C:\Users\halkony\.bun\install\global\node_modules\@vue\cli\lib\util\executeCommand.js:138:16)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.cp.emit (C:\Users\halkony\.bun\install\global\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1090:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```
**To Reproduce**
Run the `vue add electron-builder` command with any version of node.

**Expected behavior**
I expect the install to complete. Did this break because some dependencies were updated?

**Screenshots**

**Environment (please complete the following information):**
I also tried this with Node 20. Vue info says @vue/cli is missing, but I have it inside of bun globals instead.
```
vue info

Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
  Binaries:
    Node: 17.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @css-render/vue3-ssr:  0.15.14
    @cypress/vue:  0.0.0-development
    @cypress/vue2:  0.0.0-development
    @vitejs/plugin-vue: ^5.2.1 => 5.2.1
    @volar/typescript:  2.4.10
    @vue/babel-helper-vue-transform-on:  1.2.5
    @vue/babel-plugin-jsx:  1.2.5
    @vue/babel-plugin-resolve-type:  1.2.5
    @vue/compiler-core:  3.5.13
    @vue/compiler-dom:  3.5.13
    @vue/compiler-sfc:  3.5.13
    @vue/compiler-ssr:  3.5.13
    @vue/compiler-vue2:  2.7.16
    @vue/devtools-api:  6.6.4
    @vue/devtools-core:  7.6.7
    @vue/devtools-kit:  7.6.7
    @vue/devtools-shared:  7.6.7
    @vue/eslint-config-prettier: ^10.1.0 => 10.1.0
    @vue/eslint-config-typescript: ^14.1.3 => 14.1.4
    @vue/language-core:  2.1.10
    @vue/reactivity:  3.5.13
    @vue/runtime-core:  3.5.13
    @vue/runtime-dom:  3.5.13
    @vue/server-renderer:  3.5.13
    @vue/shared:  3.5.13
    @vue/test-utils: ^2.4.6 => 2.4.6
    @vue/tsconfig: ^0.7.0 => 0.7.0
    eslint-plugin-vue: ^9.30.0 => 9.32.0
    typescript: ~5.6.3 => 5.6.3
    vite-plugin-vue-devtools: ^7.6.5 => 7.6.7
    vite-plugin-vue-inspector:  5.3.1
    vue: ^3.5.13 => 3.5.13
    vue-component-type-helpers:  2.1.10
    vue-demi:  0.14.10
    vue-eslint-parser:  9.4.3
    vue-router: ^4.4.5 => 4.5.0
    vue-tsc: ^2.1.10 => 2.1.10
    vueuc:  0.4.64
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by halkony** [comment]
I tried upgrading the yarn version to 4.5 with `yarn set version stable`, which gets a successful install but has none of the after-install prompts.

```
📦  Installing vue-cli-plugin-electron-builder...

➤ YN0000: · Yarn 4.5.3
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @babel/core@npm:7.26.0, @babel/eslint-parser@npm:7.25.9, @vue/cli-plugin-babel@npm:5.0.8, and 1358 more.    
➤ YN0000: └ Completed in 1s 910ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 466 packages were added to the project (+ 58.92 MiB).
➤ YN0000: └ Completed in 3s 92ms
➤ YN0000: ┌ Link step
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ core-js@npm:3.39.0 must be built because it never has been before or the last one failed
➤ YN0007: │ yorkie@npm:2.0.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 12s 418ms
➤ YN0000: · Done with warnings in 17s 581ms
✔  Successfully installed plugin: vue-cli-plugin-electron-builder

Plugin vue-cli-plugin-electron-builder does not have a generator to invoke
```
