### ISSUE TITLE
how to build win in osx vscode??

### ISSUE THREAD

**Issue by lostshin** [nklayman/vue-cli-plugin-electron-builder#227]
when i type`npm run electron:build -- --win` I find the err:

```
INFO  Building app with electron-builder:
  • electron-builder version=20.39.0
  • description is missed in the package.json appPackageFile=/Users/chunlinlu/electron-project/dist_elect
ron/bundled/package.json
  • author is missed in the package.json appPackageFile=/Users/chunlinlu/electron-project/dist_electron/b
undled/package.json
  • writing effective config file=dist_electron/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=4.1.0 appOutDir=dist_electron/win-unpacked
  ⨯ error: exit status 1
path: /Users/chunlinlu/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine
args: /Users/chunlinlu/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine /Users/chunlinlu/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.4.0/rcedit-ia32.exe /Users/chunlinlu/electron-project/dist_electron/win-unpacked/electron-project.exe --set-version-string FileDescription electron-project --set-version-string ProductName electron-project --set-version-string LegalCopyright Copyright © 2019 electron-project --set-file-version 0.1.0 --set-product-version 0.1.0.0 --set-version-string InternalName electron-project --set-version-string OriginalFilename  --set-icon /Users/chunlinlu/electron-project/dist_electron/.icon-ico/icon.ico
output: 
error output:wine: /Users/chunlinlu/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/wine-home is not owned by you

github.com/develar/app-builder/pkg/util.Execute
        /Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
        /Volumes/data/Documents/app-builder/pkg/wine/wine.go:92
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
        /Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:78
runtime.main
        /usr/local/Cellar/go/1.12/libexec/src/runtime/proc.go:200
runtime.goexit
        /usr/local/Cellar/go/1.12/libexec/src/runtime/asm_amd64.s:1337

 ERROR  Error: /Users/chunlinlu/electron-project/node_modules/app-builder-bin/mac/app-builder exited with code 1
Error: /Users/chunlinlu/electron-project/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/chunlinlu/electron-project/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at WinPackager.signAndEditResources (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/Users/chunlinlu/electron-project/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at /Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at WinPackager.doPack (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/chunlinlu/electron-project/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/chunlinlu/electron-project/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/chunlinlu/electron-project/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/chunlinlu/electron-project/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Packager.build (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/chunlinlu/electron-project/node_modules/app-builder-lib/src/index.ts:59:28)
    at Object.build (/Users/chunlinlu/electron-project/node_modules/electron-builder/src/builder.ts:228:10)
    at buildApp (/Users/chunlinlu/electron-project/node_modules/vue-cli-plugin-electron-builder/index.js:194:14)
    at bundle.run (/Users/chunlinlu/electron-project/node_modules/vue-cli-plugin-electron-builder/index.js:176:15)
    at finalCallback (/Users/chunlinlu/electron-project/node_modules/webpack/lib/Compiler.js:214:39)
    at hooks.done.callAsync.err (/Users/chunlinlu/electron-project/node_modules/webpack/lib/Compiler.js:263:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chunlinlu/electron-project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chunlinlu/electron-project/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/chunlinlu/electron-project/node_modules/webpack/lib/Compiler.js:261:22)
    at Compiler.emitRecords (/Users/chunlinlu/electron-project/node_modules/webpack/lib/Compiler.js:375:39)
    at emitAssets.err (/Users/chunlinlu/electron-project/node_modules/webpack/lib/Compiler.js:255:10)
    at hooks.afterEmit.callAsync.err (/Users/chunlinlu/electron-project/node_modules/webpack/lib/Compiler.js:361:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chunlinlu/electron-project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chunlinlu/electron-project/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEach.err (/Users/chunlinlu/electron-project/node_modules/webpack/lib/Compiler.js:358:27)
    at /Users/chunlinlu/electron-project/node_modules/neo-async/async.js:2825:7
    at done (/Users/chunlinlu/electron-project/node_modules/neo-async/async.js:2861:11)
    at /Users/chunlinlu/electron-project/node_modules/neo-async/async.js:2813:7
    at /Users/chunlinlu/electron-project/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-project@0.1.0 electron:build: `vue-cli-service electron:build "--win"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-project@0.1.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chunlinlu/.npm/_logs/2019-03-19T08_24_54_100Z-debug.log
```

**Comment by nklayman** [comment]
It appears the issue is that your installation of wine is owned by another user account (`error output:wine: /Users/chunlinlu/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/wine-home is not owned by you`). Try re-installing wine on the same account that you are using to build the app.
