### ISSUE TITLE
TypeError: child.off is not a function; while changing background.ts file.

### ISSUE THREAD

**Issue by Setitch** [nklayman/vue-cli-plugin-electron-builder#267]
**Describe the bug**
When i change files of type ts/js in the project it crashes in dev mode with this error
  ```
TypeError: child.off is not a function
    at launchElectron (x:\node_modules\vue-cli-plugin-electron-builder\index.js:372:17)
    at bundle.run (x:\node_modules\vue-cli-plugin-electron-builder\index.js:287:13)
    at finalCallback (x:\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\Compiler.js:220:39)
    at hooks.done.callAsync.err (x:\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\Compiler.js:269:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (x:\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (x:\node_modules\tapable\lib\Hook.js:154:20)
    at emitRecords.err (x:\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\Compiler.js:267:22)
    at Compiler.emitRecords (x:\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\Compiler.js:449:39)
    at emitAssets.err (x:\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\Compiler.js:261:10)
    at hooks.afterEmit.callAsync.err (x:\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\Compiler.js:435:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (x:\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (x:\node_modules\tapable\lib\Hook.js:154:20)
    at asyncLib.forEachLimit.err (x:\node_modules\vue-cli-plugin-electron-builder\node_modules\webpack\lib\Compiler.js:432:27)
    at x:\node_modules\neo-async\async.js:2813:7
    at done (x:\node_modules\neo-async\async.js:3521:9)
    at x:\node_modules\graceful-fs\graceful-fs.js:45:10
error Command failed with exit code 1.

```

**To Reproduce**
* run    ```yarn electron:serve```
* for example change _background.ts_ file
* crashes

**Expected behavior**
reloads the app

**Environment (please complete the following information):**
- OS and version: win 8.1
- node version: 8.15
- npm version: 6.4.1
- yarn version (if used): 1.15.2
- vue-cli-plugin-electron-builder version : 1.3.1
- electron version: 5.0.1

**Comment by nklayman** [comment]
Thanks for the report, looks like `.off()` wasn't added till Node 10.
