### ISSUE TITLE
install ERROR after TypeScript

### ISSUE THREAD

**Issue by jimluo** [nklayman/vue-cli-plugin-electron-builder#27]
λ vue add electron-builder
..
success Saved 1 new dependency.
✔  Successfully installed plugin: vue-cli-plugin-electron-builder

? Do you use TypeScript? No
 ERROR  RangeError: Array buffer allocation failed
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at createUnsafeArrayBuffer (buffer.js:93:12)
    at createUnsafeBuffer (buffer.js:87:25)
    at allocate (buffer.js:293:12)
    at Function.Buffer.allocUnsafe (buffer.js:254:10)
    at tryCreateBuffer (fs.js:528:21)
    at Object.fs.readFileSync (fs.js:568:14)
    at readFiles (C:\Users\vrv\AppData\Roaming\nvm\v8.10.0\node_modules\@vue\cli\lib\invoke.js:35:12)
    at process._tickCallback (internal/process/next_tick.js:188:7)

node v8.10.0 32, vue-cli v3.0.0-rc.3
after wait 3 min typescript,  ERROR . Both npm and yarn.

**Comment by nklayman** [comment]
this is an issue with electron builder v20 or greater. As a temporary workaround, set electron-builder to `^19.0.0` in your devDependencies.

**Comment by jimluo** [comment]
Thanks, upgrade node to v8.11.3, it's works.
This tool helped me and improved work efficiency。
