### ISSUE TITLE
Doesn't work with @vue/cli v4.0.0-alpha.0

### ISSUE THREAD

**Issue by pksunkara** [nklayman/vue-cli-plugin-electron-builder#281]
**To Reproduce**
```bash
npm i -g @vue/cli@4.0.0-alpha.0
vue create --preset pksunkara/spoiler test
cd test
npm run serve # Works
vue add electron-builder
npm run electron:serve # Doesn't work
```

**Expected behavior**
`npm run electron:serve` should work

**Environment (please complete the following information):**
 - OS and version: Mac 10.14.3
 - node version: 12
 - vue-cli-plugin-electron-builder version : latest
 - electron version: Both 5 and 3

**Additional context**
```
 INFO  Starting development server...
 ERROR  TypeError: Cannot read property '__expression' of undefined
TypeError: Cannot read property '__expression' of undefined
    at Object.toConfig (/Users/pksunkara/test/node_modules/webpack-chain/src/Plugin.js:56:38)
    at /Users/pksunkara/test/node_modules/webpack-chain/src/Config.js:131:61
    at Array.map (<anonymous>)
    at module.exports.toConfig (/Users/pksunkara/test/node_modules/webpack-chain/src/Config.js:131:40)
    at Service.resolveWebpackConfig (/Users/pksunkara/test/node_modules/@vue/cli-service/lib/Service.js:236:34)
    at PluginAPI.resolveWebpackConfig (/Users/pksunkara/test/node_modules/@vue/cli-service/lib/PluginAPI.js:139:25)
    at serve (/Users/pksunkara/test/node_modules/@vue/cli-service/lib/commands/serve.js:48:31)
    at Service.run (/Users/pksunkara/test/node_modules/@vue/cli-service/lib/Service.js:221:12)
    at /Users/pksunkara/test/node_modules/vue-cli-plugin-electron-builder/index.js:249:40
    at Service.run (/Users/pksunkara/test/node_modules/@vue/cli-service/lib/Service.js:221:12)
    at Object.<anonymous> (/Users/pksunkara/test/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
```

**Comment by pksunkara** [comment]
Thanks, can I please get a minor release?

**Comment by nklayman** [comment]
Thanks for the tip! Update to v1.3.3 and it should work.
