### ISSUE TITLE
why __dirname return path of dist electron?

### ISSUE THREAD

**Issue by sanch941** [nklayman/vue-cli-plugin-electron-builder#282]
**why __dirname return path of dist electron?**
I wanna split electron background js in modules. How can i do this? I wanna get global local module from child module ,without require('../../../../globalModule'), but dirname returns path of electron dist. It solves with require(__static + 'globalModule'), but will be there other methods of splitting to modules?

**Comment by sanch941** [comment]
> **why __dirname return path of dist electron?**
> I wanna split electron background js in modules. How can i do this? I wanna get global local module from child module ,without require('../../../../globalModule'), but dirname returns path of electron dist. It solves with require(__static + 'globalModule'), but will be there other methods of splitting to modules?

**Comment by nklayman** [comment]
The `background.js` is bundled with [webpack](https://webpack.js.org/), so import statements are evaluated at compile time. You should be able to use [webpack aliases](https://webpack.js.org/configuration/resolve/#resolvealias).

**Comment by kondziu989** [comment]
@nklayman 
I have the same issue and I cannot solve it with webpack aliases, because I don't need to import any modules. Whatever settings I use for webpack node I keep getting the same path to dist_electron. 
I wasted way too many hours trying to figure it out. Any clues?

**Comment by yuhang4520** [comment]
Have you solved it?

**Comment by nancologist** [comment]
I have also the same problem , using Google Lighthouse as dependency in my application, because it apparently uses ``__dirname`` in the node_module to write reports in an html file, but in ``background.js`` when i add ``const lighthouse = require('lighthouse')`` it looks in ``dist_electron``


```
App threw an error during load
Error: ENOENT: no such file or directory, open '/Users/morjalil/Desktop/Projekte/lighthouse_vorlaeufer/google-lighthouse_abprojekt/prototype1-2/dist_electron/report-template.html'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at eval (webpack:///./node_modules/lighthouse/lighthouse-core/report/html/html-report-assets.js?:10:28)
    at Object../node_modules/lighthouse/lighthouse-core/report/html/html-report-assets.js (/Users/morjalil/Desktop/Projekte/lighthouse_vorlaeufer/google-lighthouse_abprojekt/prototype1-2/dist_electron/index.js:2560:1)
    at __webpack_require__ (/Users/morjalil/Desktop/Projekte/lighthouse_vorlaeufer/google-lighthouse_abprojekt/prototype1-2/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/lighthouse/lighthouse-core/report/report-generator.js?:8:26)
    at Object../node_modules/lighthouse/lighthouse-core/report/report-generator.js (/Users/morjalil/Desktop/Projekte/lighthouse_vorlaeufer/google-lighthouse_abprojekt/prototype1-2/dist_electron/index.js:2584:1)
    at __webpack_require__ (/Users/morjalil/Desktop/Projekte/lighthouse_vorlaeufer/google-lighthouse_abprojekt/prototype1-2/dist_electron/index.js:20:30)

```
