### ISSUE TITLE
Warn in electron serve

### ISSUE THREAD

**Issue by sanch941** [nklayman/vue-cli-plugin-electron-builder#299]
What does mean following?
 ```
WARN  Force killing Electron (process #6028)
at SDK.DOMNode._removeChild (chrome-devtools://devtools/bundled/shell.js:4301:28)
    at SDK.DOMModel._childNodeRemoved (chrome-devtools://devtools/bundled/shell.js:4420:121)
    at SDK.DOMDispatcher.childNodeRemoved (chrome-devtools://devtools/bundled/shell.js:4464:54)
    at Protocol.InspectorBackend._DispatcherPrototype.dispatch (chrome-devtools://devtools/bundled/shell.js:3399:26)
    at Protocol.SessionRouter._onMessage (chrome-devtools://devtools/bundled/shell.js:3355:41)
    at SDK.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/shell.js:3486:17)
    at Common.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:494:23)
    at innerDispatch (chrome-devtools://devtools/bundled/shell.js:972:98)
    at Host.InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/bundled/shell.js:972:1)
    at DevToolsAPIImpl._dispatchOnInspectorFrontendAPI (chrome-devtools://devtools/bundled/devtools_compatibility.js:57:36)", source: chrome-devtools://devtools/bundled/shell.js (972)
    at SDK.DOMNode._removeChild (chrome-devtools://devtools/bundled/shell.js:4301:28)
    at SDK.DOMModel._childNodeRemoved (chrome-devtools://devtools/bundled/shell.js:4420:121)
    at SDK.DOMDispatcher.childNodeRemoved (chrome-devtools://devtools/bundled/shell.js:4464:54)
    at Protocol.InspectorBackend._DispatcherPrototype.dispatch (chrome-devtools://devtools/bundled/shell.js:3399:26)
    at Protocol.SessionRouter._onMessage (chrome-devtools://devtools/bundled/shell.js:3355:41)
    at SDK.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/shell.js:3486:17)
    at Common.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:494:23)
    at innerDispatch (chrome-devtools://devtools/bundled/shell.js:972:98)
    at Host.InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/bundled/shell.js:972:1)
    at DevToolsAPIImpl._dispatchOnInspectorFrontendAPI (chrome-devtools://devtools/bundled/devtools_compatibility.js:57:36)", source: chrome-devtools://devtools/bundled/shell.js (972)
```

**Comment by ThePrinoob** [comment]
Got the same with Electron 5.0.0

**Comment by nklayman** [comment]
It looks like this is caused by electron refusing to exit gracefully. If electron can't exit properly, it is force killed.
