### ISSUE TITLE
Build failed on Win10 64bit. Can't open output file

### ISSUE THREAD

**Issue by Yuezi32** [nklayman/vue-cli-plugin-electron-builder#302]
**Describe the bug**
Build failed on Win10 64bit. But it's worked on Win7 32bit.
Error output:
Can't open output file
Error - aborting creation process

**To Reproduce**

**Expected behavior**
Build successful on Win10 64bit.

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: Win10 64bit
 - node version:  10.15.3
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.3.4
 - electron version: 5.0.2
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
Error: C:\Users\yingm\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\Bin\makensis.exe exited with code 1
        Output:
Command line defined: "APP_ID=com.electron.xinhuanet-cms"
Command line defined: "APP_GUID=77dae497-6420-5250-b1bf-c4d3e11cccbc"
Command line defined: "UNINSTALL_APP_KEY=77dae497-6420-5250-b1bf-c4d3e11cccbc"
Command line defined: "PRODUCT_NAME=xinhuanetcms"
Command line defined: "PRODUCT_FILENAME=xinhuanetcms"
Command line defined: "APP_FILENAME=xinhuanet-cms"
Command line defined: "APP_DESCRIPTION="
Command line defined: "VERSION=1.0.0"
Command line defined: "PROJECT_DIR=D:\develop\CMS-Electron-VUE"
Command line defined: "BUILD_RESOURCES_DIR=D:\develop\CMS-Electron-VUE\build"
Command line defined: "APP_PACKAGE_NAME=xinhuanet-cms"
Command line defined: "MUI_ICON=D:\develop\CMS-Electron-VUE\public\app.ico"
Command line defined: "MUI_UNICON=D:\develop\CMS-Electron-VUE\public\app.ico"
Command line defined: "APP_64=D:\develop\CMS-Electron-VUE\dist_electron\xinhuanet-cms-1.0.0-x64.nsis.7z"
Command line defined: "APP_64_NAME=xinhuanet-cms-1.0.0-x64.nsis.7z"
Command line defined: "APP_64_HASH=AC76296B3C52CF4F4BD248F8B2AC605DD8DDCAD117EA4BA7034F1D1B31D0F4484B9B018960BC3DD87B27827EC37DB870E878BCB6BDE4BDCB096DD0C621BA7634"
Command line defined: "APP_PRODUCT_FILENAME=xinhuanetcms"
Command line defined: "APP_INSTALLER_STORE_FILE=xinhuanet-cms-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=xinhuanetcms"
Command line defined: "UNINSTALL_DISPLAY_NAME=xinhuanetcms 1.0.0"
Command line defined: "ESTIMATED_SIZE=158699"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=D:\develop\CMS-Electron-VUE\dist_electron\.__uninstaller-nsis-xinhuanet-cms.exe"
Processing config: C:\Users\yingm\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

Processed 1 file, 9 command line commands, writing output (x86-unicode):

Output: "D:\develop\CMS-Electron-VUE\dist_electron\xinhuanetcms Setup 1.0.0.exe"

  Error output:
Can't open output file
Error - aborting creation process

    at ChildProcess.childProcess.once.code (D:\develop\CMS-Electron-VUE\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Comment by Yuezi32** [comment]
when update windows to 1903, solved.
