### ISSUE TITLE
Command to start already built project

### ISSUE THREAD

**Issue by Kylart** [nklayman/vue-cli-plugin-electron-builder#303]
**Is your feature request related to a problem? Please describe.**
I would love to be able to start a project easily when already built. Having to build the project whenever we need to launch it (except when built with electron-builder).

It would be convenient especially to test the built app. If I want to set up several `.spec.js`files, I don't really need the tests to go through the whole build process for every test.

**Describe the solution you'd like**
A simple `npm run start` command or programmatic mean to start this app. Ideally, it would be used in the `testWithSpectron` method.

**Describe alternatives you've considered**
None.

**Additional context**
Sometimes, the build can be really long (more than 90 seconds) and for tests suites, it's really annoying to have to wait everytime.

**Comment by nklayman** [comment]
If you have already produced an executable, you can just pass it to spectron. ie 

```js
const app = new Application({
  path: './dist_electron/PLATFORM_unpacked/APP_NAME(.exe)'
})
```

The `testWithSpectron` function is used to start the dev server and connect to that. If that is what you are doing, you should be able to create a global helper that launches spectron (via `testWithSpectron`), and export the launched instance. You should then be able to import it into your tests and run the tests on the same instance.

**Comment by Kylart** [comment]
I'm not sure to really understand what you mean, even if I give path to Spectron directly or via `testWithSpectron`, I get a build.

I'm looking for a solution than would simply start the app from the built files. That process should take only a few seconds and no build should be required as the files are already there.

**Comment by nklayman** [comment]
Can you give a full error log when you pass the path of the app to spectron directly? I tried it myself on a blank project and it worked just fine (on Ubuntu 19.04). Can you try on a blank project as well?

**Comment by Kylart** [comment]
So I tried on MacOS with a brand new project, still got the error.

Here's the error (long stack):

```
RUNTIME EXCEPTION  Exception occurred while loading your tests

Error: ENOENT: no such file or directory, scandir '/protocol'
    at Object.readdirSync (fs.js:785:3)
    at getImplementedCommands (/Users/Kylart/Desktop/test/dist/webpack:/node_modules/webdriverio/build/lib/helpers/getImplementedCommands.js:40:1)
    at Object../node_modules/webdriverio/build/index.js (/Users/Kylart/Desktop/test/dist/webpack:/node_modules/webdriverio/build/index.js:59:1)
    at __webpack_require__ (/Users/Kylart/Desktop/test/dist/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/Users/Kylart/Desktop/test/dist/webpack:/node_modules/spectron/lib/application.js:7:1)
    at Object../node_modules/spectron/lib/application.js (/Users/Kylart/Desktop/test/dist/main.js:51762:30)
    at __webpack_require__ (/Users/Kylart/Desktop/test/dist/webpack:/webpack/bootstrap:19:1)
    at Object../node_modules/spectron/index.js (/Users/Kylart/Desktop/test/dist/webpack:/node_modules/spectron/index.js:1:1)
    at __webpack_require__ (/Users/Kylart/Desktop/test/dist/webpack:/webpack/bootstrap:19:1)
    at Module../tests/unit/electron.spec.js (/Users/Kylart/Desktop/test/dist/webpack:/tests/unit/electron.spec.js:1:1)
    at __webpack_require__ (/Users/Kylart/Desktop/test/dist/webpack:/webpack/bootstrap:19:1)
    at run (/Users/Kylart/Desktop/test/dist/webpack:/node_modules/mocha-webpack/lib/entry.js:3:1)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mocha-webpack/lib/entry.js (/Users/Kylart/Desktop/test/dist/webpack:/node_modules/mocha-webpack/lib/entry.js:10:1)
    at __webpack_require__ (/Users/Kylart/Desktop/test/dist/webpack:/webpack/bootstrap:19:1)
    at /Users/Kylart/Desktop/test/dist/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/Users/Kylart/Desktop/test/dist/main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/Kylart/Desktop/test/node_modules/mocha-webpack/lib/util/registerRequireHook.js:148:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/Kylart/Desktop/test/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/Kylart/Desktop/test/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/Kylart/Desktop/test/node_modules/mocha/lib/mocha.js:576:10)
    at /Users/Kylart/Desktop/test/node_modules/mocha-webpack/lib/runner/TestRunner.js:191:27
    at /Users/Kylart/Desktop/test/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Kylart/Desktop/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Kylart/Desktop/test/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/Kylart/Desktop/test/node_modules/webpack/lib/Compiler.js:261:22)
    at Compiler.emitRecords (/Users/Kylart/Desktop/test/node_modules/webpack/lib/Compiler.js:375:39)
    at emitAssets.err (/Users/Kylart/Desktop/test/node_modules/webpack/lib/Compiler.js:255:10)
    at hooks.afterEmit.callAsync.err (/Users/Kylart/Desktop/test/node_modules/webpack/lib/Compiler.js:361:14)
    at _err0 (eval at create (/Users/Kylart/Desktop/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at callback (/Users/Kylart/Desktop/test/node_modules/copy-webpack-plugin/dist/index.js:126:17)
    at afterEmit (/Users/Kylart/Desktop/test/node_modules/copy-webpack-plugin/dist/index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Kylart/Desktop/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Kylart/Desktop/test/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEach.err (/Users/Kylart/Desktop/test/node_modules/webpack/lib/Compiler.js:358:27)
    at /Users/Kylart/Desktop/test/node_modules/neo-async/async.js:2830:7
    at done (/Users/Kylart/Desktop/test/node_modules/neo-async/async.js:2865:11)
    at /Users/Kylart/Desktop/test/node_modules/neo-async/async.js:2818:7
    at MemoryFileSystem.writeFile (/Users/Kylart/Desktop/test/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/Users/Kylart/Desktop/test/node_modules/webpack/lib/Compiler.js:342:29)
    at asyncLib.forEach (/Users/Kylart/Desktop/test/node_modules/webpack/lib/Compiler.js:352:7)
    at baseEach (/Users/Kylart/Desktop/test/node_modules/neo-async/async.js:2421:9)
    at Object.each (/Users/Kylart/Desktop/test/node_modules/neo-async/async.js:2854:9)
    at emitFiles (/Users/Kylart/Desktop/test/node_modules/webpack/lib/Compiler.js:315:13)
    at Immediate._onImmediate (/Users/Kylart/Desktop/test/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
```

And here is the test file, same as the template one, I just changed the beforeEach and afterEach hooks.

```javascript
import { Application } from 'spectron'
import chai from 'chai'
import chaiAsPromised from 'chai-as-promised'

chai.should()
chai.use(chaiAsPromised)

describe('Application launch', function () {
  this.timeout(30000)

  beforeEach(function () {
    this.app = new Application({
      path: '/Users/Kylart/Desktop/test/dist_electron/mac/test.app'
    })
    this.app.start()
  })

  beforeEach(function () {
    chaiAsPromised.transferPromiseness = this.app.transferPromiseness
  })

  afterEach(function () {
    this.app.mainProcess.exit(0)
  })

  it('opens a window', function () {
    return this.app.client
      .getWindowCount()
      .should.eventually.have.at.least(1)
      .browserWindow.isMinimized()
      .should.eventually.be.false.browserWindow.isVisible()
      .should.eventually.be.true.browserWindow.getBounds()
      .should.eventually.have.property('width')
      .and.be.above(0)
      .browserWindow.getBounds()
      .should.eventually.have.property('height')
      .and.be.above(0)
  })
})
```

**Comment by nklayman** [comment]
Unfortunately I can't test on mac, but it looks like you aren't wating for the app to launch. `app.start()` returns a promise that must be awaited before you can run any tests.

**Comment by Kylart** [comment]
@nklayman Is it possible to start a project with the `electron` cli? Usually, one can do `electron dist` to start it in production mode.

I get that with your tool it's more complicated but do you any idea if it's possible? Simple `electron dist/bundled/background.js` does not work...

**Comment by nklayman** [comment]
If it is already build, you can just launch the created executable (`dist_electron/PLATFORM_unpacked/APP_NAME(.exe)`).

**Comment by Kylart** [comment]
But I need to launch it using the `electron` cli or programatically, this won't do 🤔

**Comment by nklayman** [comment]
You should be able to use child_process to execute the built app from nodejs.

**Comment by Kylart** [comment]
Is there no way to simply start the app with the `electron` cli?

**Comment by Kylart** [comment]
Alright, so for anyone that would wander here: Yes it is possible.

In your main file, usually `background.js`
```js
// Change
if (process.env.WEBPACK_DEV_SERVER_URL) {
    // Load the url of the dev server if in development mode
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
  } else {
    ...
  }

// into
if (isDevelopment && process.env.WEBPACK_DEV_SERVER_URL && !process.env.IS_TEST) {
    // Load the url of the dev server if in development mode
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
  } else {
```

Build your project using any script based on `electron:build`

Start it with this command
```
$ ./node_modules/.bin/electron dist/bundled/background.js
```

To go further and use this for testing purposes:
I have not found any way to start tests with Babel features but I'd love to hear some.

I got rid of the mocha plugin and installed `mocha` manually. My spec file now looks like this:
```js
const { Application } = require('spectron')
const electron = require('electron')
const chai = require('chai')
const chaiAsPromised = require('chai-as-promised')

chai.should()
chai.use(chaiAsPromised)

describe('Launch app', function () {
  this.timeout(10000)

  before(async function () {
    this.app = new Application({
      path: electron,
      args: ['dist/bundled/background.js']
    })

    return this.app.start()
  })

  beforeEach(function () {
    chaiAsPromised.transferPromiseness = this.app.transferPromiseness
  })

  after(async function () {
    return this.app.stop()
  })

  it('should be visible', async function () {
    return this.app.client
      .getWindowCount()
      .should.eventually.have.at.least(1)
      .browserWindow.isMinimized()
      .should.eventually.be.false.browserWindow.isVisible()
      .should.eventually.be.true.browserWindow.getBounds()
      .should.eventually.have.property('width')
      .and.be.above(0)
      .browserWindow.getBounds()
      .should.eventually.have.property('height')
      .and.be.above(0)
  })
})
```
