### ISSUE TITLE
electron-builder auto-update module cause error

### ISSUE THREAD

**Issue by nickfan** [nklayman/vue-cli-plugin-electron-builder#323]
**Describe the bug**
i follow electron-builder auto-update instruction to add **electron-updater** to my app but when i check for update it will cause Error: ENOENT: no such file or directory

```js
  Error: Error: ENOENT: no such file or directory, open 'vcptronexp/dist_electron/dev-app-update.yml'
    at eval (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:624:70)
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.loadUpdateConfig (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:625:7)
    at Lazy.eval (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:221:58)
    at Lazy.get value [as value] (webpack:///./node_modules/lazy-val/out/main.js?:23:25)
    at eval (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:502:52)
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)

```

**To Reproduce**

i build a simple show case project for this :
https://github.com/nickfan/vcptronexp
the code is at:

```
https://github.com/nickfan/vcptronexp/blob/master/src/views/About.vue
https://github.com/nickfan/vcptronexp/blob/master/src/background.js
```

to run:

```sh
yarn install

# to build a release and latest.yml
yarn run release
# to serve the static files
yarn run publish:serve

# to run dev server and Reproduce the bug
yarn run electron:serve

```

click about tab
and click "check4Update"
the main process is at:
```js
#https://github.com/nickfan/vcptronexp/blob/master/src/background.js::184

ipcMain.on("check4update", (event, arg) => {
  (async () => {
    autoUpdater.checkForUpdates();
    event.sender.send("check4update-reply", "reply");
  })().catch(err => {
    console.log(err);
  });
});

```

**Expected behavior**

not cause ENOENT: no such file or directory;

**Screenshots**

**Environment (please complete the following information):**
 - OS and version:macos 10.14.5
 - node version: v10.15.3
 - npm version:6.9.0
 - yarn version (if used): 1.16.0
 - vue-cli-plugin-electron-builder version : ^1.3.5
 - electron version: v5.0.4
 - other vue plugins used: 
package.json
```json
{
  "name": "vcptronexp",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "release": "vue-cli-service electron:build -p always",
    "publish:serve": "http-server dist_electron -p4000",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "test:unit": "vue-cli-service test:unit"
  },
  "main": "background.js",
  "dependencies": {
    "axios": "^0.19.0",
    "axios-cookiejar-support": "^0.5.0",
    "axios-curlirize": "^1.2.0",
    "carlo": "^0.9.46",
    "chai-as-promised": "^7.1.1",
    "core-js": "^2.6.5",
    "electron-log": "^3.0.6",
    "electron-updater": "^4.0.14",
    "fs-extra": "^8.0.1",
    "http-server": "^0.11.1",
    "nedb": "^1.8.0",
    "nedb-models": "^2.2.7",
    "nedb-promises": "^3.0.6",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.8.0",
    "@vue/cli-plugin-eslint": "^3.8.0",
    "@vue/cli-plugin-unit-mocha": "^3.8.0",
    "@vue/cli-service": "^3.8.0",
    "@vue/eslint-config-prettier": "^4.0.1",
    "@vue/test-utils": "1.0.0-beta.29",
    "axios": "^0.19.0",
    "babel-eslint": "^10.0.1",
    "chai": "^4.1.2",
    "electron": "^5.0.0",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "lint-staged": "^8.1.5",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0",
    "vue-cli-plugin-axios": "0.0.4",
    "vue-cli-plugin-electron-builder": "^1.3.5",
    "vue-template-compiler": "^2.6.10"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,vue}": [
      "vue-cli-service lint",
      "git add"
    ]
  }
}

```

 - custom config for vcp-electron-builder: 
vue.config.js
```js
// import * as LodashModuleReplacementPlugin from "lodash-webpack-plugin";
// let LodashModuleReplacementPlugin;
// LodashModuleReplacementPlugin = require("lodash-webpack-plugin");
module.exports = {
  lintOnSave: true,
  pluginOptions: {
    electronBuilder: {
      externals: ["carlo"],
      customFileProtocol: "app://./",
      // customFileProtocol: 'file://./',
      baseUrl: "app://./",
      removeElectronJunk: true,
      builderOptions: {
        // options placed here will be merged with default configuration and passed to electron-builder
        appId: "me.axiong.vcptronexp.app",
        productName: "vcptronexp",
        artifactName: "${productName}.${ext}",
        compression: "store",
        mac: {
          category: "public.app-category.business",
          target: "default"
        },
        nsis: {
          oneClick: false,
          perMachine: true,
          allowToChangeInstallationDirectory: true
        },
        win: {
          target: [
            {
              target: "nsis",
              arch: ["x64", "ia32"]
            }
          ]
        },
        linux: {
          target: "AppImage"
        },
        publish: [
          {
            provider: "generic",
            url: "http://127.0.0.1:4000/",
            channel: "latest"
          }
        ]
      }
    }
  }
};

```
babel.config.js
```js
module.exports = {
  presets: [["@vue/app", { targets: { node: "current" } }]]
};

```

 - (if possible) link to your repo: 

https://github.com/nickfan/vcptronexp

**Additional context**

**Comment by nklayman** [comment]
When I run `electron:serve` on your repo, it just exits after saying "launching electron", yet electron is never launched. When I try to build, I get the following error:
```
Unhandled rejection Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping
 entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/noah/Documents/html/vcptronexp/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/home/noah/Documents/html/vcptronexp/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /home/noah/Documents/html/vcptronexp/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/home/noah/Documents/html/vcptronexp/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/home/noah/Documents/html/vcptronexp/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (/home/noah/Documents/html/vcptronexp/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (/home/noah/Documents/html/vcptronexp/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (/home/noah/Documents/html/vcptronexp/node_modules/webpack/lib/SourceMapDevToolPlugin.js:37:30)
    at files.forEach (/home/noah/Documents/html/vcptronexp/node_modules/webpack/lib/SourceMapDevToolPlugin.js:136:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (/home/noah/Documents/html/vcptronexp/node_modules/webpack/lib/SourceMapDevToolPlugin.js:130:12)
    at SyncHook.eval (eval at create (/home/noah/Documents/html/vcptronexp/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/home/noah/Documents/html/vcptronexp/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/home/noah/Documents/html/vcptronexp/node_modules/webpack/lib/Compilation.js:1313:42)
    at _err0 (eval at create (/home/noah/Documents/html/vcptronexp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
```

Can you fix these errors so I can debug the issue?

**Comment by nickfan** [comment]
Hmmm,i try to upgrade my yarn to 1.17.3 and reinstall the node_modules but i cloud not reproduce your state.
however, i simplify my project code and commit my yarn.lock file at exp1 branch,
could you checkout https://github.com/nickfan/vcptronexp/tree/exp1 
and try again?
the exception code still at about page and click the 'check4update' button.

will cause:

```
02:25:27.087 › 1check4update
02:25:27.138 › Error: Error: ENOENT: no such file or directory, open 'vcptronexp/dist_electron/dev-app-update.yml'
02:25:27.139 › 1update-error Cannot check for updates: Error: ENOENT: no such file or directory, open 'vcptronexp/dist_electron/dev-app-update.yml'
{ [Error: ENOENT: no such file or directory, open 'vcptronexp/dist_electron/dev-app-update.yml']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'vcptronexp/dist_electron/dev-app-update.yml',
  name: 'UnhandledRejection Error' }
02:25:27.144 › Error: ENOENT: no such file or directory, open 'vcptronexp/dist_electron/dev-app-update.yml'


```

**Comment by nickfan** [comment]
@nklayman have you reproduce the error, or is there anything i missed?thx.

**Comment by nklayman** [comment]
Sorry, I have been pretty busy lately, and I haven't had time to work on this. You can only use checkForUpdates in your built app, not in dev mode. In addition, you have to run it from a packaged app (ie the installer), not from `dist_electron/windows-unpacked/vcptronexp.exe`. When I build the app and install it, then run it, the issue goes away. I'm leaving for a camping trip later today, and wont be back till August 4th. I won't have cell service, so you'll be on your own for the next two weeks.

**Comment by SuperKirik** [comment]
Hello !

But dev-app-update.yml is needed for "develop/test UI/UX of updating without packaging the application",
So, is there an ability to use dev-app-update.yml  whithout having this error ?
