### ISSUE TITLE
Running completion hooks... ERROR  Error: ENOENT: no such file or directory, open 'E:\xxxx\.gitignore'

### ISSUE THREAD

**Issue by cxyao** [nklayman/vue-cli-plugin-electron-builder#36]
when the project are not used by git, Running completion hooks... ERROR  Error: ENOENT: no such file or directory, open 'E:\xxxx\.gitignore'
I'm using svn for the project, but error are outputed.
🚀  Invoking generator for vue-cli-plugin-electron-builder...
-  Running completion hooks... ERROR  Error: ENOENT: no such file or directory, open 'E:\xxx\.gitignore'
Error: ENOENT: no such file or directory, open 'E:\xxxx\.gitignore'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at api.onCreateComplete (E:\xxxx\node_modules\vue-cli-plugin-electron-builder\generator\index.js:8:24)
    at invoke (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:123:13)
    at <anonymous>

**Comment by M-Hamza-Maqbool** [comment]
just remove spaces from your foler or projact name. This will work fine
