### ISSUE TITLE
Error on build with electron and typescript

### ISSUE THREAD

**Issue by b-connect** [nklayman/vue-cli-plugin-electron-builder#42]
**Describe the bug**
Get an error message on a clean project 
```
Unhandled rejection TypeError: Cannot read property 'provider' of null
    at /home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:93:40
From previous event:
    at createUpdateInfoTasks (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/out/publish/updateInfoBuilder.js:284:18)
    at /home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/publish/PublishManager.ts:180:6
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/publish/PublishManager.ts:182:5)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/publish/PublishManager.ts:107:36)
    at EventEmitter.emit (events.js:187:15)
    at EventEmitter.emit (domain.js:442:20)
    at Packager.dispatchArtifactCreated (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/packager.ts:235:23)
    at /home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:80:19
From previous event:
    at AppImageTarget.build (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:28:44)
    at Function.buildAsyncTargets (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at LinuxPackager.packageInDistributableFormat (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at /home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at LinuxPackager.pack (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/erik/projects/apps/sippy/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/erik/projects/apps/sippy/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /home/erik/projects/apps/sippy/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/erik/projects/apps/sippy/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Packager.build (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/home/erik/projects/apps/sippy/node_modules/app-builder-lib/src/index.ts:58:28)
    at Object.build (/home/erik/projects/apps/sippy/node_modules/electron-builder/src/builder.ts:227:10)
    at bundle.run (/home/erik/projects/apps/sippy/node_modules/vue-cli-plugin-electron-builder/index.js:164:12)
    at finalCallback (/home/erik/projects/apps/sippy/node_modules/webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/home/erik/projects/apps/sippy/node_modules/webpack/lib/Compiler.js:259:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/erik/projects/apps/sippy/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/erik/projects/apps/sippy/node_modules/tapable/lib/Hook.js:35:21)
    at emitRecords.err (/home/erik/projects/apps/sippy/node_modules/webpack/lib/Compiler.js:257:22)
    at Compiler.emitRecords (/home/erik/projects/apps/sippy/node_modules/webpack/lib/Compiler.js:372:39)
    at emitAssets.err (/home/erik/projects/apps/sippy/node_modules/webpack/lib/Compiler.js:251:10)
    at hooks.afterEmit.callAsync.err (/home/erik/projects/apps/sippy/node_modules/webpack/lib/Compiler.js:358:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/erik/projects/apps/sippy/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/erik/projects/apps/sippy/node_modules/tapable/lib/Hook.js:35:21)
    at asyncLib.forEach.err (/home/erik/projects/apps/sippy/node_modules/webpack/lib/Compiler.js:355:27)
    at done (/home/erik/projects/apps/sippy/node_modules/neo-async/async.js:2854:11)
    at /home/erik/projects/apps/sippy/node_modules/neo-async/async.js:2805:7
    at /home/erik/projects/apps/sippy/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
```

**To Reproduce**

**Expected behavior**
Build without error

**Environment (please complete the following information):**
- Ubuntu 18
- Node 10
- vue-cli 3

**Additional context**

**Comment by b-connect** [comment]
Okay. You must provide a repository in package.json. Should be reflect in docs.

**Comment by TotomInc** [comment]
What do you mean by adding a repository in the package.json?

**Comment by nklayman** [comment]
Did you pass any arguments to `build:electron`? It works fine for me on linux.

**Comment by x363090973** [comment]
> Okay. You must provide a repository in package.json. Should be reflect in docs.

where  package.json do you add repository,
