### ISSUE TITLE
'find_dp0' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by justintaddei** [nklayman/vue-cli-plugin-electron-builder#432]
**Describe the bug**
`npm run build | serve | electron:build | electron:serve` all fail with the same error on a freshly installed project.

**To Reproduce**
`$ vue create app_name` <- with default options
`$ vue add electron-builder`
`$ npm run electron:serve`

**Expected behavior**
For my app to start up.

**Environment (please complete the following information):**
 - OS and version: Window 10 Home 1903
 - node version: v10.13.0
 - npm version: 6.11.0
 - vue-cli-plugin-electron-builder version : latest
 - electron version: 6.0.0
 - other vue plugins used: N/A
 - custom config for vcp-electron-builder: N/A

**Additional context**
The problem first appeared when tried to update some npm packages. I was stupid and updated a couple at a time. When I tried to start the app it crashed, so I reverted back all the packages I had updated but that didn't fix the problem. So, a little stumped, I created a new package to see if it would work... it didn't. I've even tried restoring node_modules from my backup drive but that didn't fix it either. None of __my__ source code has changed.

**The output in the console:**
```bash
justi@jComputer MINGW64 /c/dev/Opus/opus (master)
$ npm run electron:serve

> opus@0.1.0 electron:serve C:\dev\Opus\opus
> vue-cli-service electron:serve

'find_dp0' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\@vue\cli-service\bin\vue-cli-service.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by justintaddei** [comment]
I haven't tried just a straight Vue project yet. Maybe that package is corrupt on my somehow. (Not sure how it could be but it's the only one haven't reinstalled)

I'll give it a shot when I get home from church.

**Comment by nklayman** [comment]
Try deleting the `node_modules` folder and then reinstalling dependencies. If the error occurs when running the `build` or `serve` commands (non electron), then the issue is not related to this plugin, please close it.
