### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by xiaozhuai** [nklayman/vue-cli-plugin-electron-builder#508]
log:

```
yarn run v1.19.1
$ vue-cli-service electron:build --macos
 INFO  Bundling render process:

⠸  Building modern bundle for production...

 DONE  Compiled successfully in 3731ms                                                                                                                                                                       6:48:07 PM

  File                                      Size             Gzipped

  dist_electron/bundled/js/chunk-vendors    853.12 KiB       229.99 KiB
  .8ea8148d.js
  dist_electron/bundled/js/app.3602b715.    25.31 KiB        5.66 KiB
  js
  dist_electron/bundled/css/chunk-vendor    228.05 KiB       34.51 KiB
  s.728eb7d9.css
  dist_electron/bundled/css/app.a07824fa    0.06 KiB         0.07 KiB
  .css

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron/bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
(node:40591) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/xiaozhuai/wuta_project/wuta_component_merge/node_modules/vue-cli-plugin-electron-builder/index.js:139:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:40591) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40591) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 5.61s.
```

It is ok until yesterday, I use yarn 1.9.1 and node 12.11.1 on macos 10.14.6 (18G103)

**Comment by xiaozhuai** [comment]
Finally, I found what happened.
I have another project that has the same configuration but works fine.
The deference is that the broken one's package.json does not has a `dependencies` field. it's possiable, for my project, all dependencies is in `devDependencies`. So that may be a bug?

**Comment by nklayman** [comment]
Vue is a dependency of your project, so you should always have that field.
