### ISSUE TITLE
 Unknown option "report"

### ISSUE THREAD

**Issue by cawa-93** [nklayman/vue-cli-plugin-electron-builder#588]
**Describe the bug**
I'm trying to build an app with the `--report` arg.
But this leads to an error:

```
vue-cli-service electron:build --report

 Bundling render process:

 ...

 Build complete.

 Bundling main process...
 Compiled successfully

Building app with electron-builder:
  • electron-builder  version=21.2.0 os=19.0.0

/Users/Alex/Develop/play-shiki-app/node_modules/app-builder-lib/src/index.ts:44
      throw new InvalidConfigurationError(`Unknown option "${optionName}"`)
            ^
Error: Unknown option "report"
```

<details>

```
Error: Unknown option "report"
    at checkBuildRequestOptions (/Users/Alex/Develop/play-shiki-app/node_modules/app-builder-lib/src/index.ts:44:13)
    at build (/Users/Alex/Develop/play-shiki-app/node_modules/app-builder-lib/src/index.ts:50:3)
    at Object.build (/Users/Alex/Develop/play-shiki-app/node_modules/electron-builder/src/builder.ts:210:10)
    at buildApp (/Users/Alex/Develop/play-shiki-app/node_modules/vue-cli-plugin-electron-builder/index.js:212:14)
    at /Users/Alex/Develop/play-shiki-app/node_modules/vue-cli-plugin-electron-builder/index.js:194:15
    at finalCallback (/Users/Alex/Develop/play-shiki-app/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/Alex/Develop/play-shiki-app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Alex/Develop/play-shiki-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Alex/Develop/play-shiki-app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/Alex/Develop/play-shiki-app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/Alex/Develop/play-shiki-app/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/Alex/Develop/play-shiki-app/node_modules/webpack/lib/Compiler.js:298:10
    at /Users/Alex/Develop/play-shiki-app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Alex/Develop/play-shiki-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Alex/Develop/play-shiki-app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/Alex/Develop/play-shiki-app/node_modules/webpack/lib/Compiler.js:482:27

```

</details>

**To Reproduce**
```
vue-cli-service electron:build --report
```

**Expected behavior**
The application is built as usual, but it creates separate html files with the report

**Environment (please complete the following information):**
 - OS and version: macOS 10.15.1 (19B88)
 - node version: v12.13.0
 - npm version: 6.12.0
 - vue-cli-plugin-electron-builder version : 
 - electron version: 1.4.3
 - other vue plugins used: 
    - @vue/cli-plugin-typescript
    - vue-cli-plugin-vuetify

 - link to your repo: https://github.com/cawa-93/play-shikimori-online/tree/v2.0.x

**Comment by nklayman** [comment]
Thanks for the report, fixed in v`1.4.4`,
