### ISSUE TITLE
Upgrade Electron version in existing project

### ISSUE THREAD

**Issue by eschirtz** [nklayman/vue-cli-plugin-electron-builder#626]
I would like to see documentation on how to best upgrade the electron version in a pre-existing project built with this plugin. Currently running electron `^3.1.9` and feeling like a dinosaur. 

I considered re-adding `electron-builder` and forcing the initial prompt so I can pick `^6...`, then manually fixing any changed files such as `background.js`.

If there is an existing issue with this info please just let me know! Hoping to get back to a more modern version of electron.

Thanks!

**Comment by nklayman** [comment]
You should be able to just run `yarn add -D electron@^6.0.0` or `npm i -D electron@^6.0.0`. There may be a few breaking changes that you will need to take care of, the only major one I can think of is replacing
```js
protocol.registerStandardSchemes(['app'], { secure: true })
```
with
```js
protocol.registerSchemesAsPrivileged([{scheme: 'app', privileges: { secure: true, standard: true } }])
```
in `background.js`. Give it a shot and let me know if you run into any issues.

**Comment by eschirtz** [comment]
Hey,

I keep running into the following error. I've tried multiple versions of `electron` and multiple versions of `electron-builder`. In some cases it will get past `yarn` but still throw the warning and fail on `yarn electron:serve`, in the case of `electron: ^5.0.0`. But then it will hang in the install process when running `yarn` for `electron: ^6.0.0`. Same error message each time.

Have you seen anything like this?

```
gyp info using node-gyp@5.0.5
    gyp info using node@10.16.3 | darwin | x64
    gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
    gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
    gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/ericschirtzinger/Code/projects/samply/samply-desktop/node_modules/speaker/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/ericschirtzinger/.electron-gyp/5.0.13',
    gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/ericschirtzinger/.electron-gyp/5.0.13/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/ericschirtzinger/Code/projects/samply/samply-desktop/node_modules/speaker',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    ../src/binding.cc:30:27: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      ao->channels = info[1]->Int32Value(); /* channels */
                              ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8.h:2446:3: note: 'Int32Value' has been explicitly marked deprecated here
      V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
      ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated(message)))
                                ^
    ../src/binding.cc:31:23: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      ao->rate = info[2]->Int32Value(); /* sample rate */
                          ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8.h:2446:3: note: 'Int32Value' has been explicitly marked deprecated here
      V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
      ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated(message)))
                                ^
    ../src/binding.cc:32:25: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      ao->format = info[3]->Int32Value(); /* MPG123_ENC_* format */
                            ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8.h:2446:3: note: 'Int32Value' has been explicitly marked deprecated here
      V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
      ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated(message)))
                                ^
    ../src/binding.cc:51:22: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      int len = info[2]->Int32Value();
                         ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8.h:2446:3: note: 'Int32Value' has been explicitly marked deprecated here
      V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
      ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated(message)))
                                ^
    ../src/binding.cc:80:19: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      wreq->callback->Call(1, argv);
                      ^
    ../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
      NAN_DEPRECATED inline v8::Local<v8::Value>
      ^
    ../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/binding.cc:104:6: error: variable has incomplete type 'void'
    void Initialize(Handle<Object> target) {
         ^
    ../src/binding.cc:104:24: error: 'Object' does not refer to a value
    void Initialize(Handle<Object> target) {
                           ^
    /Users/ericschirtzinger/.electron-gyp/5.0.13/include/node/v8.h:3257:17: note: declared here
    class V8_EXPORT Object : public Value {
                    ^
    ../src/binding.cc:104:17: error: use of undeclared identifier 'Handle'
    void Initialize(Handle<Object> target) {
                    ^
    ../src/binding.cc:104:32: error: use of undeclared identifier 'target'
    void Initialize(Handle<Object> target) {
                                   ^
    ../src/binding.cc:104:39: error: expected ';' after top level declarator
    void Initialize(Handle<Object> target) {
                                          ^
                                          ;
    5 warnings and 5 errors generated.
    make: *** [Release/obj.target/binding/src/binding.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
    gyp ERR! System Darwin 19.2.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/ericschirtzinger/Code/projects/samply/samply-desktop/node_modules/speaker
    gyp ERR! node -v v10.16.3
    gyp ERR! node-gyp -v v5.0.5
    gyp ERR! not ok 
    error Command failed with exit code 1.
    
                                             command=/usr/local/bin/node /usr/local/Cellar/yarn/1.21.1/libexec/bin/yarn.js run install
                                             workingDir=/Users/ericschirtzinger/Code/projects/samply/samply-desktop/node_modules/speaker
```

**Comment by eschirtz** [comment]
When yarn allows me to install ( even though it still shows the error logs above ), I can get to a point where I make the change you suggested, changing `registerSchemesAsPrivileged`... 

But then when I run `yarn electron:serve` I'm faced with the following error.

```
external "url"?61e8:1 Uncaught ReferenceError: require is not defined
    at eval (external "url"?61e8:1)
    at Object.url (worker.js:1108)
    at __webpack_require__ (worker.js:786)
    at fn (worker.js:151)
    at eval (createSocketUrl.js?2ef6:4)
    at Object../node_modules/webpack-dev-server/client/utils/createSocketUrl.js (chunk-vendors.js:9793)
    at __webpack_require__ (worker.js:786)
    at fn (worker.js:151)
    at Object.eval (client?e0b3:20)
    at eval (index.js?http://localhost:177)
```

This appears to be unrelated and possibly just another breaking change. But it makes me nervous since I'm still getting that error when building `node speaker` on a yarn install. 

Thanks again,

**Comment by nklayman** [comment]
Have you tried `rm -r`ing `node_modules` and then running `yarn`? I haven't seen that specific error, but I have seen similar issues with node_gyp. The second error is because you need to manually enable `nodeintegration` on electron 5.0+ (not sure on the exact version), I forgot to mention that. To do this, add this to the config argument of `new BrowserWindow`: 
```js
webPreferences: {
  nodeIntegration: true
}
```

**Comment by eschirtz** [comment]
Looks like that did the trick! 

I did `rm -rf` `node_modules` a bunch of times with no luck. I tried upgrading this package, `vue-cli-plugin-electron-builder`, before upgrading `electron` and visa-versa. Unfortunately I don't know the exact order that ended up working in the end, wish I had something more deterministic for future reference. 

But if someone stumbles upon this later, these are the changes that worked for me. 

```
node: v10.16.3 ===>  v12.14.1
electron: v3.1.9 ===> v6.0.0
vue-cli-plugin-electron-loader v1.3.3 ===> 1.4.4
```

And the suggestions made by @nklayman above.

Thanks again

**Comment by nklayman** [comment]
The order in which you upgrade shouldn't matter. You could upgrade both at the same time, that would be the easiest. The node version shouldn't matter either. It appears most of your issues came from the speaker npm package getting rebuilt, I'm not sure why that happened though.

**Comment by eschirtz** [comment]
I hear ya,

Definitely agree that none of those things should matter. Just not sure what ended up doing the trick in the end. 

Thanks for your help!
