### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by AmrBinBashir** [nklayman/vue-cli-plugin-electron-builder#631]
**Describe the bug**
here is the output 
```
PS D:\Development\transy> vue add electron-builder                                                   WARN  There are uncommited changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

📦  Installing vue-cli-plugin-electron-builder...

yarn add v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠁ electron-chromedriver                                                                       error D:\Development\transy\node_modules\electron-chromedriver: Command failed.
Exit code: 1
Command: node ./download-chromedriver.js
Arguments:
Directory: D:\Development\transy\node_modules\electron-chromedriver
Output:
internal/modules/cjs/loader.js:321
      throw err;
      ^

Error: Cannot find module 'D:\Development\transy\node_modules\readable-stream\readable.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:313:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:693:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Development\transy\node_modules\concat-stream\index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'D:\\Development\\transy\\node_modules\\readable-stream\\package.json',
  requestPath: 'readable-stream'
}
                                                                                                     ERROR  command failed: yarn add vue-cli-plugin-electron-builder -D --registry=https://registry.yarnpkg.com
```
**To Reproduce**
1- vue create your-app
2- vue add electron-builder

**Environment (please complete the following information):**
 - OS and version: win 10 1909
 - node version: 13.5
 - npm version: 6.13.4
 - yarn version (if used): 1.21.1
 - vue-cli-plugin-electron-builder version : 
 - electron version: 
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo:

**Comment by AmrBinBashir** [comment]
Looks like something was wrong on my machine, i did yarn cache clear then tried to install and it worked
