### ISSUE TITLE
Cannot create portable windows build on Linux system. 

### ISSUE THREAD

**Issue by nikhileshva** [nklayman/vue-cli-plugin-electron-builder#673]
**Describe the bug**
Whenever I run `yarn electron:build -mwl`, the build for macOS and Linux works fine, but windows build gives an error. 

**To Reproduce**
I'm running this on a Linux system, however everything works fine when I build it on macOS. 

**Expected behavior**
That I get an .exe file after running the command. 

**Screenshots**
```
11:30:40  [INFO]   • building        target=portable file=dist_electron/dmt-38.0.0-20200228091755-7f116a6-dev-win-exe-win.exe archs=x64
11:30:41  [INFO]   • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.2/nsis-3.0.3.2.7z size=1.4 MB parts=1
11:30:42  [INFO]   • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.2/nsis-3.0.3.2.7z duration=1.709s
11:33:07  [INFO]   • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z size=731 kB parts=1
11:33:07  [INFO]   • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z duration=1.513s
11:33:07  [ERROR]  ERROR  Error: /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
11:33:07  [ERROR] Error output:
11:33:07  [ERROR]        
11:33:07  [ERROR] Error output:
11:33:07  [ERROR] /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis)
11:33:07  [ERROR] /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis)
11:33:07  [ERROR]        
11:33:07  [ERROR]     at ChildProcess.<anonymous> (/data/jenkins/workspace/IntegratorTool_Build_dev_win-exe/node_modules/builder-util/src/util.ts:239:14)
11:33:07  [ERROR]     at Object.onceWrapper (events.js:300:26)
11:33:07  [ERROR]     at ChildProcess.emit (events.js:210:5)
11:33:07  [ERROR]     at ChildProcess.EventEmitter.emit (domain.js:475:20)
11:33:07  [ERROR]     at maybeClose (internal/child_process.js:1021:16)
11:33:07  [ERROR]     at Socket.<anonymous> (internal/child_process.js:430:11)
11:33:07  [ERROR]     at Socket.emit (events.js:210:5)
11:33:07  [ERROR]     at Socket.EventEmitter.emit (domain.js:475:20)
11:33:07  [ERROR]     at Pipe.<anonymous> (net.js:659:12)
11:33:07  [ERROR] error Command failed with exit code 1.
```
**Environment (please complete the following information):**
 - OS and version: Amazon AMI
 - node version: 10.16.0
 - npm version: 6.9.0
 - yarn version (if used): 1.16.0
 - vue-cli-plugin-electron-builder version : 1.4.2
 - electron version: 4.0.8
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
```
builderOptions: {
        win: {
          'signAndEditExecutable': false,
          target: [
            'portable'
          ]
        },
        portable: {
          artifactName: '${name}-${version}-${os}.exe'
        },
```

**Comment by nklayman** [comment]
Looks like you are missing a required dep. Make sure you have installed all the packages installed in this [Dockerfile](https://github.com/electron-userland/electron-builder/blob/master/docker/wine/Dockerfile). You can also [use docker to build for other platforms](https://www.electron.build/multi-platform-build#docker). Specifically, it looks like `glibc` is missing:
```
11:33:07  [ERROR] /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis)
11:33:07  [ERROR] /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/jenkins-slave/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis)
```

**Comment by nikhileshva** [comment]
Works with Docker. Thanks for pointing out.
