### ISSUE TITLE
Issue running/building when native modules are required.

### ISSUE THREAD

**Issue by smithalan92** [nklayman/vue-cli-plugin-electron-builder#73]
**Describe the bug**
I have a simple app, with a few customisations.

`src` has been renamed to `renderer`

`background.js` has been moved from `src` into a new folder called `main`

and I have updated the main process file in `vue.conf.js` 

The app runs correctly if I don't use native modules, however when I require a native module, for example

'const afk = require('afk')`' which is a module for detecting user inactivity

I get the following error

```
[ './node_modules/desktop-idle/index.js\nModule not found: Error: Can\'t resolve \'./build/Release/desktopIdle\' in \'/Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle\'\nresolve \'./build/Release/desktopIdle\' in \'/Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle\'\n  using description file: /Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/package.json (relative path: .)\n    using description file: /Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/package.json (relative path: ./build/Release/desktopIdle)\n      no extension\n        /Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle doesn\'t exist\n      .wasm\n        /Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle.wasm doesn\'t exist\n      .mjs\n        /Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle.mjs doesn\'t exist\n      .js\n        /Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle.js doesn\'t exist\n      .json\n        /Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle.json doesn\'t exist\n      as directory\n        /Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle doesn\'t exist\n[/Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle]\n[/Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle.wasm]\n[/Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle.mjs]\n[/Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle.js]\n[/Users/Alan/Desktop/dev/electron-test/node_modules/desktop-idle/build/Release/desktopIdle.json]\n @ ./node_modules/desktop-idle/index.js 1:20-58\n @ ./node_modules/afk/NodeAFK.js\n @ ./main/desktopStatus.js\n @ ./main/ipc.js\n @ ./main/app.js\n @ ./main/index.js\n @ multi ./main/index.js' ]
```

If I add that to my vue.config.js as an electron builder external, and try another module like

`const notificationState = require('electron-notification-state`)` 

which is a module for detecting user if a notification should be displayed or not, the build will fail with 

```
[ './node_modules/bindings/bindings.js 81:22-40\nCritical dependency: the request of a dependency is an expression\n    at RequireResolveContextDependency.getWarnings (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/dependencies/ContextDepend
    ency.js:40:18)\n    at Compilation.reportDependencyErrorsAndWarnings (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compilation.js:1325:24)\n    at Compilation.finish (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compil
    ation.js:1136:9)\n    at hooks.make.callAsync.err (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compiler.js:545:17)\n    at _err0 (eval at create (/Users/Alan/Desktop/dev/electron-test/node_modules/tapable/lib/HookCodeFactory.js:24:12),
     <anonymous>:11:1)\n    at _addModuleChain (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compilation.js:1064:12)\n    at processModuleDependencies.err (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compilation.js:980:9)
    \n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n @ ./node_modules/windows-notification-state/lib/index.js\n @ ./node_modules/electron-notification-state/lib/index.j
    s\n @ ./main/Notifications.js\n @ ./main/ipc.js\n @ ./main/app.js\n @ ./main/index.js\n @ multi ./main/index.js',  './node_modules/bindings/bindings.js 81:43-53\nCritical dependency: the request of a dependency is an expression\n    at CommonJsRequireContextDependency.getWarnings (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/dependencies/ContextDepen
    dency.js:40:18)\n    at Compilation.reportDependencyErrorsAndWarnings (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compilation.js:1325:24)\n    at Compilation.finish (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compi
    lation.js:1136:9)\n    at hooks.make.callAsync.err (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compiler.js:545:17)\n    at _err0 (eval at create (/Users/Alan/Desktop/dev/electron-test/node_modules/tapable/lib/HookCodeFactory.js:24:12)
    , <anonymous>:11:1)\n    at _addModuleChain (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compilation.js:1064:12)\n    at processModuleDependencies.err (/Users/Alan/Desktop/dev/electron-test/node_modules/webpack/lib/Compilation.js:980:9
    )\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n @ ./node_modules/windows-notification-state/lib/index.js\n @ ./node_modules/electron-notification-state/lib/index.
    js\n @ ./main/Notifications.js\n @ ./main/ipc.js\n @ ./main/app.js\n @ ./main/index.js\n @ multi ./main/index.js' ]
```

I also have the following warning

```
WARNING in ./node_modules/bindings/bindings.js 81:22-40
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/windows-notification-state/lib/index.js
 @ ./node_modules/electron-notification-state/lib/index.js
 @ ./main/Notifications.js
 @ ./main/ipc.js
 @ ./main/app.js
 @ ./main/index.js
 @ multi ./main/index.js

WARNING in ./node_modules/bindings/bindings.js 81:43-53
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/windows-notification-state/lib/index.js
 @ ./node_modules/electron-notification-state/lib/index.js
 @ ./main/Notifications.js
 @ ./main/ipc.js
 @ ./main/app.js
 @ ./main/index.js
 @ multi ./main/index.js

```

and finally

```
Launching Electron...
App threw an error during load
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at dirname (path.js:1364:5)
    at Function.getRoot (webpack:///./node_modules/bindings/bindings.js?:151:13)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:60:32)
    at eval (webpack:///./node_modules/macos-notification-state/lib/index.js?:1:89)
    at Object../node_modules/macos-notification-state/lib/index.js (/Users/Alan/Desktop/develectron-test/dist_electron/background.js:405:76)
```

Any help would be great 😀

**Environment (please complete the following information):**
 - OS and version: MacOS High Sierra 
 - Node version: 8.11.4
 - npm version: 5.6.0
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.2
 - other vue plugins used: 
 - custom config for vcp-electron-builder:

```
module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.node$/,
          use: 'node-loader',
        },
      ],
    },
    resolve: {
      alias: {
        '@': `${__dirname}/renderer`,
      },
    },
    entry: {
      app: './renderer/main.js',
    },
  },
  pluginOptions: {
    electronBuilder: {
      mainProcessFile: 'main/index.js',
      externals: [
        'afk',
      ],
    },
  },
};
```

**Comment by nklayman** [comment]
I'm having issues building the `afk` modules, so I can't test that. However, I got the `electron-notification-state` to work by adding it to the externals list. Also, you may need to re-invoke the generator (`vue invoke electron-builder`) as the native modules code may be missing (it was added in 1.0.0-rc.1).

**Comment by nklayman** [comment]
Also, does this work if you don't change the custom directories? Please create a blank project and test using the `afk` module. Thanks.
