### ISSUE TITLE
Can't build my project, because dist directory structure is different than expected

### ISSUE THREAD

**Issue by major-mayer** [nklayman/vue-cli-plugin-electron-builder#845]
Hi,
first things first, thank you for this really great vue plugin :)
Using `npm run electron:build` works, but not the build command, because apparently it exepects a `src` folder in the `\dist_electron\win-unpacked\resources\app\` directory.
But for my instance there is no `src` folder generated, all the files (including the background.js which it complains about) are just directly in the app folder without any subfolder.

Did I configure something wrong, or do I have to specify the correct output folder to make the build process work again?

```
PS C:\***\velectron> npm run electron:build

> velectron@0.1.0 electron:build C:***\velectron
> vue-cli-service electron:build

 INFO  Bundling render process:

/  Building modern bundle for production...

 DONE  Compiled successfully in 80260ms                                                                                                                                                                                  17:23:34
  File                                      Size             Gzipped   

  dist_electron\bundled\js\chunk-vendors    2978.38 KiB      666.85 KiB
  .177e7b78.js
  dist_electron\bundled\js\app.0ad3410c.    6.96 KiB         2.58 KiB  
  js
  dist_electron\bundled\css\app.5c9713c3    0.25 KiB         0.19 KiB  
  .css

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron\bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

/  Bundling main process...

 DONE  Compiled successfully in 2787ms                                                                                                                                                                                   17:23:38
  File                                   Size              Gzipped  

  dist_electron\bundled\background.js    160.52 KiB        49.43 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=22.7.0 os=10.0.18363
  • description is missed in the package.json  appPackageFile=C:***\velectron\dist_electron\bundled\package.json
  • author is missed in the package.json  appPackageFile=C:***\velectron\dist_electron\bundled\package.json     
  • writing effective config  file=dist_electron\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=9.0.4 appOutDir=dist_electron\win-unpacked
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
(node:8944) UnhandledPromiseRejectionWarning: Error: Application entry file "C:***\velectron\dist_electron\win-unpacked\resources\app\src\background.js" does not exist. Seems like a wrong configuration.
    at WinPackager.checkFileInPackage (C:***\velectron\node_modules\app-builder-lib\src\platformPackager.ts:431:15)
    at WinPackager.sanityCheckPackage (C:***\velectron\node_modules\app-builder-lib\src\platformPackager.ts:456:5)
    at WinPackager.doPack (C:***\velectron\node_modules\app-builder-lib\src\platformPackager.ts:243:5)
    at WinPackager.pack (C:***\velectron\node_modules\app-builder-lib\src\platformPackager.ts:115:5)
    at Packager.doBuild (C:***\velectron\node_modules\app-builder-lib\src\packager.ts:444:9)
    at executeFinally (C:***\velectron\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:***\velectron\node_modules\app-builder-lib\src\packager.ts:373:31)
    at Packager.build (C:***\velectron\node_modules\app-builder-lib\src\packager.ts:337:12)
    at executeFinally (C:***\velectron\node_modules\builder-util\src\promise.ts:12:14)
(node:8944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nklayman** [comment]
Please post your configuration as well.

**Comment by major-mayer** [comment]
Here you go:

```
var webpack = require('webpack');
const path = require('path')

// Add the jswrapper directory to the Path, so that all dlls can be found
let currentPath = process.env.Path;
let dllDirectory = path.dirname( path.resolve(require.resolve('moduleworks-js-wrapper/package.json'))) + `${path.sep}build${path.sep}Release` 
process.env.Path = currentPath + dllDirectory;

module.exports = {
  configureWebpack: {
    devtool: 'source-map',
  },
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      // List native deps here if they don't work
      externals: ['moduleworks-js-wrapper' ],
      // If you are using Yarn Workspaces, you may have multiple node_modules folders
      // List them all here so that VCP Electron Builder can find them
      nodeModulesPath: ['../../node_modules', './node_modules'],
      builderOptions: {
        // options placed here will be merged with default configuration and passed to electron-builder
        asar : false
      }
    }
  }
}
```

**Comment by nklayman** [comment]
Can you also post the `dist_electron\builder-effective-config.yaml` file. It looks like there is some electron-builder config that is causing the problem.

**Comment by major-mayer** [comment]
Of course, if it helps solving this issue i will provide you as much infos as I can.

`directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
asar: false
electronVersion: 9.0.4
`

**Comment by nklayman** [comment]
That looks good, not sure what is wrong then. Can you also post your `package.json`, seems like the `main` field may be misconfigured there.

**Comment by major-mayer** [comment]
Hmm I'm not sure but that's also looking good for me: 
``` 
  "name": "velectron",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "./src/background.js",
  "dependencies": {
    "babylonjs": "^4.1.0",
    "core-js": "^3.6.5",
    "moduleworks-js-wrapper": "git+ssh://git@git.moduleworks.com:laurenz/jswrapper.git",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vue-static": "0.0.5",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.4.0",
    "@vue/cli-plugin-router": "~4.4.0",
    "@vue/cli-plugin-vuex": "~4.4.0",
    "@vue/cli-service": "~4.4.0",
    "electron": "^9.0.0",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.2",
    "vue-template-compiler": "^2.6.11"
  }
}
```

**Comment by major-mayer** [comment]
Yes thanks for the tip with the "main" field, that was the case for the not working build 👍 😄 
I just needed to change it to "./background.js", i guess this was the default value too... so my fault sorry
