### ISSUE TITLE
electron-builder command line options creates error

### ISSUE THREAD

**Issue by IcyPalm** [nklayman/vue-cli-plugin-electron-builder#863]
**Describe the bug**
When using the --config option to select another electron-builder config file the effective config is suddenly written to `dist\builder-effective-config.yaml` instead of `dist_electron\builder-effective-config.yaml`

**To Reproduce**
Have a electron-builder.json in the project root
Two script options in `package.json`
    
     "electron:build": "vue-cli-service electron:build",
     "electron:test": "vue-cli-service electron:build --config 'electron-builder.json'",

The `electron:test` script gives an error

**Log Output**
When using the  `electron:build` script as shown above this is the output:

```
"C:\Program Files\nodejs\node.exe" "C:\Program Files (x86)\Yarn\bin\yarn.js" run electron:build
yarn run v1.22.4
$ vue-cli-service electron:build
 INFO  Bundling render process:
|  Building modern bundle for production...
 DONE  Compiled successfully in 12522ms                                                                                                                                                                                     16:10:41

  File                                      Size             Gzipped

  dist_electron\bundled\js\chunk-vendors    8173.84 KiB      1677.00 KiB
  .js
  dist_electron\bundled\js\app.js           2033.28 KiB      547.74 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron\bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

\  Bundling main process...

 DONE  Compiled successfully in 764ms                                                                                                                                                                                       16:10:42

  File                                   Size              Gzipped

  dist_electron\bundled\background.js    1055.46 KiB       217.95 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=21.2.0 os=10.0.19041
  • loaded configuration  file=PROJECTFOLDER\electron-builder.json
  • writing effective config  file=dist_electron\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@serialport/bindings@8.0.8, node-sass@4.14.1, sqlite3@4.2.0 platform=win32 arch=x64
  • install prebuilt binary  name=@serialport/bindings version=8.0.8 platform=win32 arch=x64
  • [NATIVE DEPENDENCY OUTPUT(not relevant)]

  • rebuilding native dependency  name=@serialport/bindings version=8.0.8
  • rebuilding native dependency  name=node-sass version=4.14.1
  • rebuilding native dependency  name=sqlite3 version=4.2.0
  • packaging       platform=win32 arch=x64 electron=8.2.5 appOutDir=dist_electron\win-unpacked
  • building        target=nsis file=dist_electron\APPLICATIONNAME.exe archs=x64 oneClick=false perMachine=true
  • building block map  blockMapFile=dist_electron\APPLICATIONNAME.exe.blockmap
 DONE  Build complete!
Done in 73.06s.
```
When using the config option this is the output
```
"C:\Program Files\nodejs\node.exe" "C:\Program Files (x86)\Yarn\bin\yarn.js" run electron:test
yarn run v1.22.4
$ vue-cli-service electron:build --config electron-builder.json
 INFO  Bundling render process:
\  Building modern bundle for production...
 DONE  Compiled successfully in 9924ms                                                                                                                                                                                      16:12:24

  File                                      Size             Gzipped

  dist_electron\bundled\js\chunk-vendors    8173.84 KiB      1677.00 KiB
  .js
  dist_electron\bundled\js\app.js           2033.28 KiB      547.74 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron\bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

/  Bundling main process...

 DONE  Compiled successfully in 1038ms                                                                                                                                                                                      16:12:26

  File                                   Size              Gzipped

  dist_electron\bundled\background.js    1055.46 KiB       217.95 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=21.2.0 os=10.0.19041
  • loaded configuration  file=PROJECTFOLDER\electron-builder.json
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@serialport/bindings@8.0.8, node-sass@4.14.1, sqlite3@4.2.0, @serialport/bindings@8.0.7 platform=win32 arch=x64
  • install prebuilt binary  name=@serialport/bindings version=8.0.8 platform=win32 arch=x64
  • [NATIVE DEPENDENCY OUTPUT(not relevant)]

  • rebuilding native dependency  name=@serialport/bindings version=8.0.8
  • rebuilding native dependency  name=node-sass version=4.14.1
  • rebuilding native dependency  name=sqlite3 version=4.2.0
  • packaging       platform=win32 arch=x64 electron=8.2.5 appOutDir=dist\win-unpacked
 ERROR  Error: Application entry file "background.js" in the "PROJECTDIR\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
Error: Application entry file "background.js" in the "PROJECTDIR\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (PROJECTDIR\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:7:12)
    at checkFileInArchive (PROJECTDIR\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:33:11)
    at WinPackager.checkFileInPackage (PROJECTDIR\node_modules\app-builder-lib\src\platformPackager.ts:402:7)
    at WinPackager.sanityCheckPackage (PROJECTDIR\node_modules\app-builder-lib\src\platformPackager.ts:453:5)
    at WinPackager.doPack (PROJECTDIR\node_modules\app-builder-lib\src\platformPackager.ts:242:5)
    at WinPackager.pack (PROJECTDIR\node_modules\app-builder-lib\src\platformPackager.ts:114:5)
    at Packager.doBuild (PROJECTDIR\node_modules\app-builder-lib\src\packager.ts:437:9)
    at executeFinally (PROJECTDIR\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (PROJECTDIR\node_modules\app-builder-lib\src\packager.ts:366:31)
    at Packager.build (PROJECTDIR\node_modules\app-builder-lib\src\packager.ts:330:12)
    at executeFinally (PROJECTDIR\node_modules\builder-util\src\promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1

```

**Environment (please complete the following information):**
 - OS and version: Windows 10(20.04) Build 19041.329
 - node version:   v12.16.1
 - npm version:
 - yarn version (if used): 1.22.4
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 8.2.5

**Comment by nklayman** [comment]
That's because you are overriding the config defaults set by this plugin. See [configuring electron builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder) for the proper way to adjust electron builder config.
