### ISSUE TITLE
Can't use Element UI

### ISSUE THREAD

**Issue by laSinteZ** [nklayman/vue-cli-plugin-electron-builder#9]
I am trying to use `electron-builder` with `element-ui` plugin https://github.com/Seb-L/vue-cli-plugin-element-ui (all this plugin does is basically installs element-ui and adds

```
import ElementUI from 'element-ui'
import locale from 'element-ui/lib/locale/lang/en'
import './styles.scss'

Vue.use(ElementUI, { locale })
```
to main.js), but when I run `yarn serve:electron` it fails with 

```
 ERROR in ./src/main.js
  Module build failed: Error: .plugins[1][1] must be an object, false, or undefined
      at assertPluginItem (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/@babel/core/lib/config/validation/option-assertions.js:185:15)
      at /Users/la.sintez/Projects/bca-sora-desktop/node_modules/@babel/core/lib/config/validation/option-assertions.js:162:14
      at Array.forEach (<anonymous>)
      at assertPluginList (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/@babel/core/lib/config/validation/option-assertions.js:161:9)
      at /Users/la.sintez/Projects/bca-sora-desktop/node_modules/@babel/core/lib/config/validation/options.js:89:20
      at Array.forEach (<anonymous>)
      at validate (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/@babel/core/lib/config/validation/options.js:67:21)
      at loadPrivatePartialConfig (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/@babel/core/lib/config/partial.js:38:48)
      at Object.loadPartialConfig (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/@babel/core/lib/config/partial.js:77:16)
      at Object.<anonymous> (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/babel-loader/lib/index.js:82:26)
      at Generator.next (<anonymous>)
      at step (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/babel-loader/lib/index.js:3:221)
      at _next (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/babel-loader/lib/index.js:3:409)
      at /Users/la.sintez/Projects/bca-sora-desktop/node_modules/babel-loader/lib/index.js:3:477
      at new Promise (<anonymous>)
      at Object.<anonymous> (/Users/la.sintez/Projects/bca-sora-desktop/node_modules/babel-loader/lib/index.js:3:97)
   @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server css-hot-loader/hotModuleReplacement ./node_modules/electron-webpack/vue-renderer-entry.js ./src/main.js
```

After I googled for a while, it seems what a problem lies in babel 7, but I am not sure :(

element-ui is possible to use with electron, since I did it with https://github.com/SimulatedGREG/electron-vue earlier.

Any idea on how to fix it? ^^

**Comment by nklayman** [comment]
Thanks for the notice, updated in v3.0.1.
