### ISSUE TITLE
cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible

### ISSUE THREAD

**Issue by jsbay** [nklayman/vue-cli-plugin-electron-builder#994]
**Describe the bug**
When i try to pack a .exe with arch32 and arch 'x64' on my macbook, i got an error:
```bash
cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
```
But, if i remove arch32 it can work well

here is my `builderOptions` in `vue.config.js`
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['serialport'],
      builderOptions: {
        appId: 'com.xxxx.xxxx',
        productName: 'xxxxx',
        copyright: 'Copyright © xxxxx.com',
        win: {
          icon: './favicon.ico',
          target: [
            {
              target: 'nsis',
              arch: [
                'x64',
                'ia32' // delete this line, will work well
              ]
            }
          ]
        },
        linux: {
          icon: './favicon.ico',
          target: [
            'snap'
          ]
        }
      }
    }
  }
};

```
**To Reproduce**
1. Input `yarn electron:build --win` and press enter,  in terminal;
2. wait a few time;
3. get an error like title

**Environment (please complete the following information):**
 - mac: macOS Catalina 10.15.6
```json
// package.json
{
  "name": "electron",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "serialport": "^9.0.0",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-property-decorator": "^8.4.2"
  },
  "devDependencies": {
    "@types/electron-devtools-installer": "^2.2.0",
    "@types/node": "^12.0.0",
    "@types/serialport": "^8.0.1",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "^4.4.0",
    "@vue/cli-plugin-eslint": "^4.4.0",
    "@vue/cli-plugin-typescript": "^4.4.0",
    "@vue/cli-service": "^4.4.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "@vue/eslint-config-typescript": "^5.0.2",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^6.2.2",
    "lint-staged": "^9.5.0",
    "tslint-config-standard": "^9.0.0",
    "typescript": "~3.9.3",
    "vue-cli-plugin-electron-builder": "^2.0.0-rc.4",
    "vue-template-compiler": "^2.6.11"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,vue,ts,tsx}": [
      "vue-cli-service lint",
      "git add"
    ]
  }
}

```

Is it cause my macbook is x64?

**Comment by nklayman** [comment]
Can you please post the full output from `electron:builde`?

**Comment by jsbay** [comment]
```
➜  electron git:(master) ✗ yarn electron:build --win        
yarn run v1.22.4
$ vue-cli-service electron:build --win
 INFO  Bundling render process:

⠋  Building modern bundle for production...Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
⠏  Building modern bundle for production...

 DONE  Compiled successfully in 5474ms                                                                                                                                        上午8:42:25

  File                                                  Size                                                           Gzipped

  dist_electron/bundled/js/chunk-vendors.b9af0ab1.js    81.79 KiB                                                      28.83 KiB
  dist_electron/bundled/js/app.c5b03a36.js              8.32 KiB                                                       2.44 KiB
  dist_electron/bundled/css/app.7be72abd.css            0.33 KiB                                                       0.23 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron/bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
      
⠏  Bundling main process...

 DONE  Compiled successfully in 960ms                                                                                                                                         上午8:42:27

  File                                   Size                                                                   Gzipped

  dist_electron/bundled/background.js    194.95 KiB                                                             60.39 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=22.8.0 os=19.6.0
  • description is missed in the package.json  appPackageFile=/Users/jsbay/electron/electron/dist_electron/bundled/package.json
  • author is missed in the package.json  appPackageFile=/Users/jsbay/electron/electron/dist_electron/bundled/package.json
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@serialport/bindings@9.0.1 platform=win32 arch=x64
  • install prebuilt binary  name=@serialport/bindings version=9.0.1 platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=9.2.1 appOutDir=dist_electron/win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • rebuilding native dependencies  dependencies=@serialport/bindings@9.0.1 platform=win32 arch=ia32
  • install prebuilt binary  name=@serialport/bindings version=9.0.1 platform=win32 arch=ia32
  ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 5.3.5
    prebuild-install info looking for cached prebuild @ /Users/jsbay/.npm/_prebuilds/cca835-bindings-v9.0.1-electron-v80-win32-ia32.tar.gz
    prebuild-install http request GET https://github.com/serialport/node-serialport/releases/download/@serialport/bindings@9.0.1/bindings-v9.0.1-electron-v80-win32-ia32.tar.gz
    prebuild-install http 404 https://github.com/serialport/node-serialport/releases/download/@serialport/bindings@9.0.1/bindings-v9.0.1-electron-v80-win32-ia32.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=9.2.1 runtime=electron arch=ia32 libc= platform=win32)
    
                                    command=/Users/jsbay/.nvm/versions/node/v14.5.0/bin/node '/Users/jsbay/electron/electron/node_modules/prebuild-install/bin.js' --platform=win32 --arch=ia32 --target=9.2.1 --runtime=electron --verbose --force
                                    workingDir=/Users/jsbay/electron/electron/node_modules/@serialport/bindings
(node:77092) UnhandledPromiseRejectionWarning: Error: /Users/jsbay/electron/electron/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/jsbay/electron/electron/node_modules/builder-util/src/util.ts:243:14)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:77092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:77092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 21.82s.
```
Here is the full output, thanks for reply.

**Comment by nklayman** [comment]
Sorry for the lack of response, I tried myself and got the same error but couldn't fix it. It seems that they don't publish prebuilt 32bit versions of the binary. Since your computer is 32bit, it can't build it from source either. I'd suggest trying from a 32 bit VM. This issue is related to serialport rather than the plugin, so I'd suggest opening an issue there if you can't figure it out.

**Comment by jsbay** [comment]
Thanks :heart: :heart:
